"""A published page may not offer a link that cannot resolve.

THE DEFECT THIS EXISTS FOR. The site-wide footer carried
``https://validant.ai/contact`` on all 18 pages that have a footer.
``https://validant.ai/contact`` returns 404, and had done since at least
2026-08-22, when the project's own docs-validation register recorded it as "the
only live call to action in the entire Support section ... is a dead link". Six
days later it was still on every page. That is not a link that rotted quietly in
a corner: it was the one way a reader was offered to get in touch.

A second family had the same shape and a worse cause. Twelve prominent
call-to-action blocks linked to
``github.com/validantai/vfairness/blob/main/notebooks/<name>.ipynb``. Those can
never resolve in the public repository, because ``notebooks`` is on the export
script's EXCLUDES list: the saved ``.ipynb`` outputs embed local development
paths, so the directory is deliberately never published. The links were not
stale, they were structurally impossible, and no check could see that because
each one is a perfectly well-formed URL.

WHAT THIS FILE CHECKS, and why in this shape.

1. **A registry of URLs verified dead**, with the date and the command. This is
   offline and deterministic: a network link-checker in a unit test is a test
   that fails on a train. The registry is a fact recorded once and enforced
   forever, which is what the 2026-08-22 finding needed and did not get.
2. **Repository paths the publish boundary deletes.** Derived from a recorded
   list rather than from the export script, which lives in the private monorepo
   and is not part of this repository at all.
3. **Every relative link resolves**, file and ``#fragment`` alike, which is a
   whole class the two registries above cannot reach.

An opt-in live check is included for the case a maintainer wants it, and it is
SKIPPED unless ``VFAIRNESS_CHECK_EXTERNAL_LINKS=1``. It is stated here plainly
rather than left to look like coverage: **it does not run in CI**, so nothing in
this repository re-verifies the registry automatically. What the registry is, is
a fact that was checked by hand on a stated date and is enforced from then on.
"""

from __future__ import annotations

import os
import re
from html import unescape
from pathlib import Path
from typing import Dict, List, Set, Tuple
from urllib.parse import unquote, urlparse

import pytest

LIB_ROOT = Path(__file__).resolve().parents[1]
SITE = LIB_ROOT / "docs" / "site"

_HREF_RE = re.compile(r'href="([^"]+)"')
_ID_RE = re.compile(r'\bid="([^"]+)"')
_NAME_RE = re.compile(r'\bname="([^"]+)"')


# --------------------------------------------------------------------------
# 1. URLs verified dead. Add to this only after checking, and say when.
# --------------------------------------------------------------------------

DEAD_URLS: Dict[str, str] = {
    "https://validant.ai/contact": (
        "404 on 2026-08-22 (docs/audits/docs-validation-findings-2026-08-22.md) and again on "
        "2026-08-28. Verified not to be bot-blocking or a SPA artifact: /imprint and /privacy "
        "answer 200 to the identical request, and /contact returns the same generic shell as a "
        "path that was never published. The footer 'Contact' entry points at "
        "https://validant.ai/imprint#publisher instead, which is where the site publishes its "
        "own contact addresses."
    ),
}

# Paths inside the public repository that the publish boundary deletes, so a
# link into them is a promise the published repository cannot keep. Recorded
# here rather than read from the export script, which is not part of this
# repository.
UNPUBLISHED_REPO_PATHS: Dict[str, str] = {
    # "notebooks" WAS here, and this is the entry coming OFF the list rather than
    # onto it. The export dropped the directory because saved .ipynb outputs
    # embedded local development paths, so twelve call-to-action blocks had to be
    # downgraded from links to plain notes. On 2026-09-07 the six offending paths
    # (in two of thirteen notebooks, all inside captured warning output) were
    # replaced with placeholders and the directory was published, so those twelve
    # are real links again. `notebooks/output` stays unpublished, below.
    "notebooks/output": (
        "47 files, 5.6 MB, every one of them regenerated by running the notebook that "
        "produced it. The notebooks themselves ARE published; their saved artifacts are "
        "not, so a link into this directory cannot resolve for a reader."
    ),
    "docs/audits": (
        "audit records are internal and are dropped by the export, so a link into them from a "
        "published page cannot resolve for a reader."
    ),
    "spikes": "dropped by the export as internal work.",
}

# Repository paths a page may name in prose. Restricted to two trees that exist
# in the published repository as well as this one.
_REPO_PATH_RE = re.compile(r"(?:tests|src/vfairness)/[A-Za-z0-9_./-]+\.(?:py|svg|json)")

# A cited pytest node id: `tests/test_x.py::TestY::test_z`.
_NODE_ID_RE = re.compile(r"tests/[A-Za-z0-9_/]+\.py::[A-Za-z0-9_:]+")

_REPO_BLOB_RE = re.compile(
    r"https://github\.com/validantai/vfairness/(?:blob|tree|raw)/[^/]+/([^\s\"#?]+)"
)


def site_pages() -> Dict[Path, str]:
    pages = {path: path.read_text(encoding="utf-8") for path in sorted(SITE.rglob("*.html"))}
    assert pages, f"no HTML under {SITE}; every check in this file would pass by finding nothing"
    return pages


def hrefs(html: str) -> List[str]:
    return _HREF_RE.findall(html)


def dead_link_problems(pages: Dict[Path, str], registry: Dict[str, str] = DEAD_URLS) -> List[str]:
    problems: List[str] = []
    for path, html in sorted(pages.items()):
        for href in hrefs(html):
            for dead, why in registry.items():
                if href == dead or href.startswith(dead + "?") or href.startswith(dead + "#"):
                    rel = (
                        path.relative_to(SITE)
                        if SITE in path.parents or path.parent == SITE
                        else path
                    )
                    problems.append(f"{rel}: links to {href}, recorded dead. {why}")
    return problems


def unpublished_path_problems(
    pages: Dict[Path, str], registry: Dict[str, str] = UNPUBLISHED_REPO_PATHS
) -> List[str]:
    problems: List[str] = []
    for path, html in sorted(pages.items()):
        for match in _REPO_BLOB_RE.finditer(html):
            target = match.group(1)
            for prefix, why in registry.items():
                if target == prefix or target.startswith(prefix + "/"):
                    rel = path.relative_to(SITE) if path.is_relative_to(SITE) else path
                    problems.append(
                        f"{rel}: links to the repository path {target!r}, which is never "
                        f"published: {why}"
                    )
    return problems


# --------------------------------------------------------------------------
# 3. Relative links resolve, target file and #fragment alike.
# --------------------------------------------------------------------------

_IGNORED_SCHEMES = ("http:", "https:", "mailto:", "tel:", "javascript:", "data:")


def _anchors(html: str) -> Set[str]:
    return set(_ID_RE.findall(html)) | set(_NAME_RE.findall(html))


def _resolve(page: Path, target: str) -> "Path | None":
    """Where a href lands on disk, the way the host serves this site.

    A leading ``/`` is site-root-relative, not filesystem-root-relative: getting
    that wrong reports every link in the 404 page as broken. Clean URLs are
    honoured too (``/concepts/changelog`` is ``concepts/changelog.html``), which
    is how the pages are actually written and served.
    """
    base = SITE if target.startswith("/") else page.parent
    candidate = (base / target.lstrip("/")).resolve()
    if candidate.is_dir():
        index = candidate / "index.html"
        return index if index.is_file() else None
    if candidate.is_file():
        return candidate
    with_html = candidate.with_name(candidate.name + ".html")
    if with_html.is_file():
        return with_html
    return None


def relative_link_problems(pages: Dict[Path, str]) -> List[str]:
    """Every non-external href must name a file that exists, and an anchor that exists.

    A fragment on the CURRENT page is checked against that page. A fragment on
    another page is checked against that page's ids, which is what caught a
    hand-written cross-page anchor that pointed at a section id nobody had
    written.
    """
    problems: List[str] = []
    anchor_cache: Dict[Path, Set[str]] = {}

    def anchors_of(path: Path) -> Set[str]:
        if path not in anchor_cache:
            anchor_cache[path] = _anchors(path.read_text(encoding="utf-8"))
        return anchor_cache[path]

    for path, html in sorted(pages.items()):
        rel = path.relative_to(SITE)
        own = _anchors(html)
        for href in hrefs(html):
            if href.startswith(_IGNORED_SCHEMES) or href.startswith("//"):
                continue
            parsed = urlparse(href)
            fragment = unquote(parsed.fragment)
            target_path = unquote(parsed.path)
            if not target_path:
                if fragment and fragment not in own and fragment != "":
                    problems.append(f"{rel}: '#{fragment}' names no id on this page")
                continue
            resolved = _resolve(path, target_path)
            if resolved is None:
                problems.append(
                    f"{rel}: href {href!r} names no file under docs/site (tried the path itself, "
                    "+'.html', and its index.html)"
                )
                continue
            if fragment and resolved.suffix == ".html" and fragment not in anchors_of(resolved):
                problems.append(
                    f"{rel}: href {href!r} names the anchor '#{fragment}', which "
                    f"{resolved.relative_to(SITE)} does not define"
                )
    return problems


# --------------------------------------------------------------------------
# The pins
# --------------------------------------------------------------------------


def test_the_sweep_reads_every_shipped_page_and_finds_links() -> None:
    """Guard against a vacuous run before trusting any result below."""
    pages = site_pages()
    assert len(pages) >= 18, len(pages)
    total = sum(len(hrefs(html)) for html in pages.values())
    assert total > 500, f"only {total} hrefs found across {len(pages)} pages; the parser is broken"


def test_no_published_page_links_to_a_url_recorded_dead() -> None:
    problems = dead_link_problems(site_pages())
    assert not problems, "\n".join(problems)


def test_no_published_page_links_into_a_path_the_export_deletes() -> None:
    problems = unpublished_path_problems(site_pages())
    assert not problems, "\n".join(problems)


def test_every_relative_link_and_anchor_resolves() -> None:
    problems = relative_link_problems(site_pages())
    assert not problems, f"{len(problems)} unresolvable links:\n" + "\n".join(problems)


def test_every_repository_path_named_on_a_page_exists() -> None:
    """A page that points at a file must point at a file that is there.

    ``docs/site/quality-and-hardening/index.html`` reported a failing test by
    name, in a "What Is Still Open" table dated the same day, after the test had
    been replaced. That is the same defect as a dead link, in prose: a pointer
    into the repository that no longer resolves. Restricted to ``tests/`` and
    ``src/vfairness/``, which exist in both the development repository and the
    published one, so this cannot go red on day one in the public repo the way a
    check over ``docs/audits/`` would.
    """
    problems: List[str] = []
    for path, raw in sorted(site_pages().items()):
        text = unescape(raw)
        for named in sorted(set(_REPO_PATH_RE.findall(text))):
            if not (LIB_ROOT / named).exists():
                problems.append(f"{path.relative_to(SITE)}: names {named!r}, which does not exist")
    assert not problems, "\n".join(problems)


def test_every_test_named_as_a_node_id_in_the_docs_exists() -> None:
    """A document that cites a test by node id must cite one that is there.

    ``docs/QUALITY_AND_HARDENING.md`` and its published page reported a red
    build under "What Is Still Open", dated the same day, naming
    ``test_changelog_unreleased_section_is_empty``. That test had been replaced;
    the failure it described was closed and the page still advertised it. The
    inverse of the fabrication class the rest of this project chases, and it
    reads as current state to anybody who lands there.

    The rule is deliberately narrow: it fires only on a FULL ``file.py::name``
    node id, which is a pointer, and not on a bare function name, which is how a
    historical record refers to something that no longer exists.
    """
    sources: Dict[str, str] = {}
    for path in sorted(SITE.rglob("*.html")):
        sources[str(path.relative_to(LIB_ROOT))] = unescape(path.read_text(encoding="utf-8"))
    for path in sorted((LIB_ROOT / "docs").glob("*.md")):
        sources[str(path.relative_to(LIB_ROOT))] = path.read_text(encoding="utf-8")

    problems = node_id_problems(sources, _collected_test_names())
    assert not problems, "\n".join(problems)


def node_id_problems(sources: Dict[str, str], known: Dict[str, Set[str]]) -> List[str]:
    """Cited node ids that name no module, or no test inside the module they name."""
    problems: List[str] = []
    for where, text in sorted(sources.items()):
        for node_id in sorted(set(_NODE_ID_RE.findall(text))):
            module, _, name = node_id.partition("::")
            leaf = name.rsplit("::", 1)[-1]
            if module not in known:
                problems.append(f"{where}: cites {node_id}, but {module} does not exist")
            elif leaf not in known[module]:
                problems.append(f"{where}: cites {node_id}, but {module} defines no {leaf}")
    return problems


def _collected_test_names() -> Dict[str, Set[str]]:
    """Every ``def test_*`` per test module, read from the source.

    Parsed rather than collected through pytest: this runs inside a pytest
    session already, and the question here is only whether a name a document
    points at is present in the file it names.
    """
    found: Dict[str, Set[str]] = {}
    for path in sorted((LIB_ROOT / "tests").rglob("*.py")):
        key = str(path.relative_to(LIB_ROOT))
        found[key] = set(
            re.findall(
                r"^\s*(?:async )?def (test_[A-Za-z0-9_]+)", path.read_text(encoding="utf-8"), re.M
            )
        ) | set(re.findall(r"^class (Test[A-Za-z0-9_]+)", path.read_text(encoding="utf-8"), re.M))
    return found


def test_the_footer_still_offers_a_way_to_make_contact() -> None:
    """The repair must not be "delete the call to action".

    Removing the dead link would satisfy every check above and leave a reader
    with no way to reach anyone, which is a worse page than the broken one.
    """
    pages = site_pages()
    with_footer = [p for p, html in pages.items() if ">Contact</a>" in html]
    assert len(with_footer) >= 18, (
        f"only {len(with_footer)} pages carry a footer Contact entry; it was on 18"
    )
    for path in with_footer:
        html = pages[path]
        match = re.search(r'href="([^"]+)"[^>]*>Contact</a>', html)
        assert match, path
        assert match.group(1) not in DEAD_URLS, path


# --------------------------------------------------------------------------
# The checks, checked
# --------------------------------------------------------------------------


class TestTheseChecksAreThemselvesChecked:
    """Plant each defect and require it to be reported.

    Everything here is a synthetic page held in memory; no repository file is
    read or written, so these controls keep working whatever the real pages say.
    """

    def _page(self, html: str) -> Dict[Path, str]:
        return {SITE / "probe.html": html}

    def test_the_dead_footer_link_is_caught(self) -> None:
        problems = dead_link_problems(
            self._page('<li><a href="https://validant.ai/contact" target="_blank">Contact</a></li>')
        )
        assert problems, "the exact link that shipped on 18 pages passed the check"
        assert "validant.ai/contact" in problems[0]

    def test_a_query_string_does_not_launder_a_dead_link(self) -> None:
        problems = dead_link_problems(
            self._page('<a href="https://validant.ai/contact?src=docs">c</a>')
        )
        assert problems, problems

    def test_a_live_link_on_the_same_host_is_not_caught(self) -> None:
        assert (
            dead_link_problems(self._page('<a href="https://validant.ai/imprint#publisher">c</a>'))
            == []
        )

    def test_a_link_into_the_notebook_artifact_directory_is_caught(self) -> None:
        """The detector still fires on a genuinely unpublished path.

        This control used to plant a link to a NOTEBOOK, because the whole
        directory was unpublished. The notebooks were published on 2026-09-07, so
        that link is now legitimate and the control had to move to a path that is
        still excluded: their regenerated artifact directory. Retargeting it,
        rather than deleting it, is what keeps the detector proven.
        """
        problems = unpublished_path_problems(
            self._page(
                '<a href="https://github.com/validantai/vfairness/blob/main/notebooks/'
                'output/bias_audit.svg">Artifact</a>'
            )
        )
        assert problems, "a link into the excluded notebooks/output/ directory passed the check"
        assert "notebooks/output" in problems[0]

    def test_a_link_to_a_notebook_itself_is_not_caught(self) -> None:
        """The inverse, which is the half that would have gone unnoticed.

        Twelve documentation call-to-action blocks point at these notebooks. If
        the registry ever re-excludes the directory, or the prefix match widens
        from `notebooks/output` to `notebooks`, every one of them starts failing
        and this says so immediately.
        """
        assert not unpublished_path_problems(
            self._page(
                '<a href="https://github.com/validantai/vfairness/blob/main/notebooks/'
                'vfairness_4_metrics_demo.ipynb">Demo</a>'
            )
        ), "a link to a PUBLISHED notebook was reported as unpublishable"

    def test_a_link_to_a_published_repository_path_is_not_caught(self) -> None:
        assert (
            unpublished_path_problems(
                self._page(
                    '<a href="https://github.com/validantai/vfairness/blob/main/docs/'
                    'DIVERGENCES.md">Divergences</a>'
                )
            )
            == []
        )

    def test_a_prefix_that_only_looks_like_an_excluded_path_is_not_caught(self) -> None:
        # `notebooks_archive` is not `notebooks`; a substring test would refuse it.
        assert (
            unpublished_path_problems(
                self._page(
                    '<a href="https://github.com/validantai/vfairness/blob/main/'
                    'notebooks_archive/x.md">x</a>'
                )
            )
            == []
        )

    def test_the_stale_test_citation_is_caught(self) -> None:
        """The exact string that shipped: a red build reported by a test that was gone."""
        known = {
            "tests/test_docs_truth.py": {"test_changelog_top_section_is_the_unreleased_version"}
        }
        problems = node_id_problems(
            {
                "docs/QUALITY_AND_HARDENING.md": (
                    "One test is failing on `main`. "
                    "`tests/test_docs_truth.py::test_changelog_unreleased_section_is_empty` asserts"
                )
            },
            known,
        )
        assert problems and "defines no" in problems[0], problems

    def test_a_citation_of_a_module_that_is_gone_is_caught(self) -> None:
        problems = node_id_problems(
            {"page.html": "see tests/test_deleted_module.py::test_a"},
            {"tests/test_docs_truth.py": {"test_a"}},
        )
        assert problems and "does not exist" in problems[0], problems

    def test_a_live_citation_is_not_caught(self) -> None:
        assert (
            node_id_problems(
                {"page.html": "see tests/test_docs_truth.py::test_a"},
                {"tests/test_docs_truth.py": {"test_a"}},
            )
            == []
        )

    def test_a_bare_function_name_is_not_treated_as_a_citation(self) -> None:
        # A historical record naming a test that no longer exists writes the bare
        # name for exactly this reason; the rule must leave it alone.
        assert (
            node_id_problems({"page.html": "test_changelog_unreleased_section_is_empty"}, {}) == []
        )

    def test_a_class_scoped_node_id_resolves_by_its_leaf(self) -> None:
        assert (
            node_id_problems(
                {"page.html": "tests/test_x.py::TestThing::test_a"},
                {"tests/test_x.py": {"test_a", "TestThing"}},
            )
            == []
        )

    def test_a_relative_link_to_a_missing_file_is_caught(self) -> None:
        problems = relative_link_problems(self._page('<a href="nowhere/index.html">x</a>'))
        assert problems and "names no file" in problems[0], problems

    def test_a_clean_url_that_does_resolve_is_not_caught(self) -> None:
        # `/concepts/changelog` is served from concepts/changelog.html; a checker
        # that demanded the extension would report every such link as broken and
        # then be deleted for crying wolf.
        assert (
            relative_link_problems({SITE / "probe.html": '<a href="/concepts/changelog">x</a>'})
            == []
        )

    def test_a_root_relative_link_resolves_against_the_site_root(self) -> None:
        assert relative_link_problems({SITE / "legal" / "probe.html": '<a href="/">home</a>'}) == []

    def test_a_fragment_that_names_no_anchor_is_caught(self) -> None:
        problems = relative_link_problems(
            self._page('<h1 id="here">t</h1><a href="#nowhere">x</a>')
        )
        assert problems and "names no id" in problems[0], problems

    def test_a_fragment_that_does_exist_is_not_caught(self) -> None:
        assert relative_link_problems(self._page('<h1 id="here">t</h1><a href="#here">x</a>')) == []

    def test_a_cross_page_fragment_is_checked_against_that_page(self) -> None:
        problems = relative_link_problems(
            {SITE / "probe.html": '<a href="api-reference/index.html#not-a-section">x</a>'}
        )
        assert problems and "does not define" in problems[0], problems


# --------------------------------------------------------------------------
# Opt in, and NOT part of CI. Stated so the registry above is not mistaken for
# a live check.
# --------------------------------------------------------------------------


@pytest.mark.skipif(
    os.environ.get("VFAIRNESS_CHECK_EXTERNAL_LINKS") != "1",
    reason="opt-in network check; set VFAIRNESS_CHECK_EXTERNAL_LINKS=1 to run it",
)
def test_every_external_link_answers(capsys: pytest.CaptureFixture) -> None:
    """Re-verify the registry by hand, in three states rather than two.

    Deliberately not enabled in CI. A network check that runs on every push turns
    an unrelated outage into a red build and gets disabled, at which point it is
    a guard that cannot fail. Run it before a release instead.

    THE THREE STATES MATTER HERE MORE THAN USUAL. The first version of this
    check failed 403 and treated it as dead. Twenty-two of the links on this
    site are ``doi.org`` and publisher URLs that answer 403 to any script, plus
    two font-CDN preconnect ORIGINS that are not pages at all. Reported as
    failures they are noise, and a check that cries wolf gets deleted, which is
    the same end state as a check that cannot fail. So:

    * **dead** (404 / 410 / a host that does not resolve) fails this test;
    * **could not check** (403, 405, 429, a TLS chain this interpreter cannot
      build, a timeout) is PRINTED and does not fail, because it is not evidence
      the page is gone;
    * a floor on the number verified live stops the whole run passing by
      checking nothing.
    """
    import urllib.error
    import urllib.request

    urls: Set[str] = set()
    for html in site_pages().values():
        for href in hrefs(html):
            if not href.startswith("http"):
                continue
            # A bare origin in a <link rel="preconnect"> is not a page.
            if not urlparse(href).path.strip("/"):
                continue
            urls.add(unescape(href))

    dead: List[Tuple[str, str]] = []
    unchecked: List[Tuple[str, str]] = []
    live = 0
    for url in sorted(urls):
        request = urllib.request.Request(
            url, headers={"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)"}
        )
        try:
            with urllib.request.urlopen(request, timeout=30) as response:  # noqa: S310
                if response.status in {404, 410}:
                    dead.append((url, str(response.status)))
                elif response.status >= 400:
                    unchecked.append((url, str(response.status)))
                else:
                    live += 1
        except urllib.error.HTTPError as exc:
            (dead if exc.code in {404, 410} else unchecked).append((url, str(exc.code)))
        except Exception as exc:  # noqa: BLE001  - never silently pass
            unchecked.append((url, f"{type(exc).__name__}: {exc}"))

    with capsys.disabled():
        print(f"\nexternal links: {live} live, {len(dead)} dead, {len(unchecked)} could not check")
        for url, why in unchecked:
            print(f"  could not check: {url} -> {why}")
    assert live >= 30, f"only {live} links verified live; this run established almost nothing"
    assert not dead, "\n".join(f"{u} -> {c}" for u, c in dead)


# --------------------------------------------------------------------------
# 5. The shipped MARKDOWN, which everything above this line never looked at
# --------------------------------------------------------------------------
#
# Everything above scans `docs/site/**/*.html`. README.md is not in there, and it
# is the first thing a PyPI visitor sees: the project description rendered on the
# package page is this file. It carries nine links of the form
# `github.com/validantai/vfairness/blob/main/<path>`.
#
# Those nine 404 TODAY, and that is expected and temporary: the public repository
# still holds only LICENSE and README until the export is pushed. What is NOT
# recoverable is a link whose target the export never ships, or whose path is
# simply wrong. That link 404s on the day the repository is populated and keeps
# 404ing, with nothing to notice it, which is exactly how the twelve notebook
# links recorded at the top of this file happened.
#
# Verified by hand 2026-09-07 against a built export tree: all nine targets ship.
# This turns that one-off check into a standing one.

_MD_LINK_RE = re.compile(r"\]\(\s*(<[^>]+>|[^)\s]+)")


def shipped_markdown() -> Dict[Path, str]:
    """Markdown a reader of the published repository can open.

    docs/audits is excluded deliberately: it is internal, the export drops it
    (see UNPUBLISHED_REPO_PATHS), so a link inside it can never mislead a reader.
    """
    paths = sorted(LIB_ROOT.glob("*.md")) + sorted(LIB_ROOT.glob("docs/*.md"))
    pages = {p: p.read_text(encoding="utf-8") for p in paths}
    assert pages, f"no shipped markdown found under {LIB_ROOT}"
    return pages


def _blob_targets(text: str) -> List[str]:
    """Repository paths named by a blob link, in MARKDOWN.

    _REPO_BLOB_RE was written for HTML, where the URL ends at the closing quote
    of an href. In markdown it is `](url)`, so the match runs on into the closing
    paren and whatever punctuation follows it, and the path is reported as
    'NOTICE).' instead of 'NOTICE'. Trim at the paren, then strip trailing
    sentence punctuation.
    """
    out: List[str] = []
    for m in _REPO_BLOB_RE.finditer(text):
        target = m.group(1).split(")")[0].rstrip(".,;:")
        if target:
            out.append(target)
    return out


def test_every_repository_link_in_shipped_markdown_points_at_a_real_file() -> None:
    """A blob link to a path that does not exist 404s forever, silently."""
    problems: List[str] = []
    for path, text in sorted(shipped_markdown().items()):
        for target in _blob_targets(text):
            if not (LIB_ROOT / target).exists():
                problems.append(
                    f"{path.relative_to(LIB_ROOT)}: links to {target!r}, which does not "
                    f"exist in this repository, so it will 404 in the public one too"
                )
    assert not problems, "\n".join(problems)


def test_no_shipped_markdown_links_into_a_path_the_export_deletes() -> None:
    problems = unpublished_path_problems(shipped_markdown())
    assert not problems, "\n".join(problems)


def _md_urls(text: str) -> List[str]:
    """Absolute URLs a markdown link points at.

    dead_link_problems() cannot be reused here: it extracts `href="..."`, which
    markdown does not contain, so it silently returns nothing. That made the
    first version of this test pass while a link to a URL recorded dead sat in
    README.md, which the sabotage run caught and a review would not have.
    """
    out: List[str] = []
    for m in _MD_LINK_RE.finditer(text):
        url = m.group(1).strip("<>")
        if url.startswith(("http://", "https://")):
            out.append(url.split(" ")[0].rstrip(".,;:"))
    return out


def test_no_shipped_markdown_links_to_a_url_recorded_dead() -> None:
    problems: List[str] = []
    for path, text in sorted(shipped_markdown().items()):
        for url in _md_urls(text):
            for dead, why in DEAD_URLS.items():
                if url == dead or url.startswith(dead + "?") or url.startswith(dead + "#"):
                    problems.append(
                        f"{path.relative_to(LIB_ROOT)}: links to {url}, recorded dead. {why}"
                    )
    assert not problems, "\n".join(problems)


def test_the_markdown_sweep_actually_reads_the_readme_and_finds_links() -> None:
    """NON-VACUITY. Three tests above would pass forever on an empty scan, and
    the README is the specific file they exist to protect."""
    pages = shipped_markdown()
    readme = LIB_ROOT / "README.md"
    assert readme in pages, "README.md is not being scanned"
    blob_links = [t for text in pages.values() for t in _blob_targets(text)]
    assert len(blob_links) >= 5, (
        f"only {len(blob_links)} repository links found across the shipped markdown; "
        "the extractor is broken"
    )
    assert _blob_targets(pages[readme]), "no repository links found in README.md itself"
    urls = [u for text in pages.values() for u in _md_urls(text)]
    assert len(urls) >= 10, (
        f"only {len(urls)} absolute URLs extracted from the shipped markdown; the "
        "dead-link scan above would be checking almost nothing"
    )
