"""Public API surface snapshot test (VB-API-3).

This test pins the exported public surface of ``vfairness`` so that any
unintended addition or removal of a public name fails CI.

    * EXPECTED_ALL is the sorted snapshot of ``vfairness.__all__``.
    * EXPECTED_PUBLIC_SUBMODULES is the sorted set of non-underscore names
      that ``dir(vfairness)`` exposes beyond ``__all__`` (the package's public
      subpackages that get bound as attributes on import).

INTENTIONAL CHANGES: adding or removing a public name is a real API change.
When you do it on purpose you must (1) update the relevant snapshot constant
below in the SAME commit, and (2) add a CHANGELOG.md entry describing the
addition/removal/rename. A failing diff here is the guardrail that forces
that discipline; do not "fix" it by blindly copy-pasting the new surface
without recording the change.
"""

import json
import os
import subprocess
import sys

import vfairness as v

EXPECTED_ALL = [
    "ADASYNResampler",
    "ActionBiasAnalyzer",
    "AdaptiveThresholdManager",
    "AdversarialCollusionDetector",
    "AlertPayload",
    "AssessmentReport",
    "BaseCalibrator",
    "BaseFeatureTransformer",
    "BaseReweighter",
    "BaseThresholdOptimizer",
    "BenchmarkRunner",
    "BetaCalibrator",
    "BiasAuditReport",
    "BiasDetector",
    "BiasMonitor",
    "BrierDecomposition",
    "CLASSIFICATION_METRICS",
    "CalibratedEqualizer",
    "CalibrationAnalyzer",
    "CalibrationCurveResult",
    "CalibrationDisparityResult",
    "CalibrationMethod",
    "CalibrationMetricResult",
    "CalibrationRecommendation",
    "CalibrationReport",
    "CapabilityStatus",
    "CausalDecomposition",
    "CoTFaithfulnessAnalyzer",
    "ColumnRole",
    "CompositionalityAnalyzer",
    "ConfigurationError",
    "ContingencyTestResult",
    "CorrelationReducer",
    "CorrespondenceTester",
    "CounterfactualAugmenter",
    "CounterfactualTester",
    "DashboardConfig",
    "DataBiasValidator",
    "DataInfo",
    "DataValidationConfig",
    "DataValidationResult",
    "DecodingTrustRunner",
    "DelegationRoutingAuditor",
    "DesignType",
    "DisparateImpactRemover",
    "DistributionMatcher",
    "DriftAlert",
    "DriftResult",
    "EmergentBiasDetector",
    "ExperimentAnalysis",
    "ExperimentConfig",
    "ExperimentParetoPoint",
    "ExperimentRecommendation",
    "ExperimentResult",
    "ExplanationReport",
    "ExplanationsReport",
    "FairClassifier",
    "FairClassifierResult",
    "FairExplAIner",
    "FairRegressor",
    "FairRepresentationTransformer",
    "FairnessAlertPrioritizer",
    "FairnessAnalyzer",
    "FairnessAssertionError",
    "FairnessConstraintType",
    "FairnessDashboard",
    "FairnessDriftDetector",
    "FairnessExperiment",
    "FairnessExplainer",
    "FairnessMonitor",
    "FairnessMonitorConfig",
    "FairnessPowerAnalyzer",
    "FairnessReport",
    "FairnessReportCard",
    "FairnessTestResult",
    "FairnessTestSuite",
    "FairnessViolation",
    "FeatureAnalysisReport",
    "FeatureCorrelationMatrix",
    "FeatureEngineeringAnalyzer",
    "FeatureProxyResult",
    "FeatureSuppressor",
    "GateConfig",
    "GateDecision",
    "GateStatus",
    "GeneratedReport",
    "GroupAdvantage",
    "GroupCalibrationResult",
    "GroupCalibrator",
    "GroupThresholdOptimizer",
    "GroupthinkDetector",
    "HISTORICAL_RISK_PATTERNS",
    "HealthScore",
    "HierarchicalGateConfig",
    "HistogramBinning",
    "HistoricalPatternResult",
    "InsufficientDataError",
    "InsufficientEvidenceGroup",
    "IntegratedCalibrationResult",
    "InteractiveConfig",
    "InteractiveDashboard",
    "IntersectionEffect",
    "IntersectionalAnalyzer",
    "IntersectionalCalibrator",
    "IntersectionalGateDecision",
    "IntersectionalTransformer",
    "IntervalType",
    "InvalidDataError",
    "InversePropensityWeighter",
    "IsotonicCalibrator",
    "KNOWN_PROXY_PATTERNS",
    "LLMApiProxy",
    "LabelMassager",
    "MetricEvaluation",
    "MetricExplanation",
    "MetricResult",
    "MetricStatusEntry",
    "MetricsStore",
    "MetricsStoreConfig",
    "ModelFairnessGate",
    "MonitorConfig",
    "MonitoringResult",
    "MultiAgentRunHarness",
    "MultiObjectiveThresholdOptimizer",
    "MulticalibrationResult",
    "MultipleTestingResult",
    "MultiscaleDriftResult",
    "MultivariateProxyResult",
    "NegotiationFairnessTracker",
    "NonDeterminismAnalyzer",
    "OutputAnalyzer",
    "OutputFormat",
    "ParetoPoint",
    "PermutationTestResult",
    "PipelineTracker",
    "PlattScaling",
    "PowerConfig",
    "PowerResult",
    "PredictionReweighter",
    "PrivacyLevel",
    "PropensityScoreWeighter",
    "ProtectedAttributeCandidate",
    "ProtectedAttributeError",
    "ProxyRiskLevel",
    "ProxyType",
    "ProxyVariableResult",
    "RAGBiasAnalyzer",
    "RECOMMENDED_BOOTSTRAP_SAMPLES",
    "REGRESSION_METRICS",
    "RankingFairnessResult",
    "RecommendationDecision",
    "RejectionOptionClassifier",
    "ReportConfig",
    "ReportGenerator",
    "ReportTier",
    "RepresentationBiasResult",
    "Resampler",
    "ResidualTransformer",
    "ReweightingAnalysisReport",
    "ReweightingAnalyzer",
    "ReweightingImpactResult",
    "ReweightingMethod",
    "ReweightingResult",
    "ReweightingTransformer",
    "RobustMetricsResult",
    "SMALL_SAMPLE_THRESHOLD",
    "SMOTEResampler",
    "SPRTDecision",
    "STATISTICAL_MEASURES",
    "SamplingPlan",
    "SensitivityResult",
    "SequentialTestResult",
    "SmallSampleWarning",
    "StatisticalDisparityResult",
    "StatisticalResult",
    "StoredMetricRecord",
    "SubgroupAuditResult",
    "SurfaceStatus",
    "SyntheticResampler",
    "TemperatureScaling",
    "TemporalFairnessAnalyzer",
    "TemporalStabilityResult",
    "TemporalTracker",
    "ThresholdAnalysisReport",
    "ThresholdAnalyzer",
    "ThresholdConstraint",
    "ThresholdImpactResult",
    "ThresholdOptimizer",
    "ThresholdResult",
    "TimeWindow",
    "TomekResampler",
    "ToolBiasAuditor",
    "TradeoffAnalysisResult",
    "TransformationResult",
    "UnknownCapabilityError",
    "VfairnessError",
    "WindowMetrics",
    "accuracy_parity_difference",
    "analyze_calibration_fairness_tradeoff",
    "analyze_intersectional_correlations",
    "analyze_statistical_disparities",
    "apply_multiple_testing_correction",
    "assert_fairness",
    "assign_clusters",
    "attention_weighted_rank_fairness",
    "attribute_historical_pattern",
    "auroc_parity",
    "auto_log_fairness",
    "bayesian_difference_ci",
    "bayesian_mean_ci",
    "bayesian_proportion_ci",
    "benjamini_hochberg_correction",
    "bonferroni_correction",
    "bootstrap_ci",
    "branding_enabled",
    "brier_score",
    "brier_score_decomposition",
    "calibration_curve",
    "calibration_difference",
    "calibration_disparity",
    "calibration_in_the_large",
    "calibration_slope",
    "calibration_vs_error_parity",
    "check_fairness_config",
    "check_model_card",
    "classification_fairness_report",
    "classify_column_roles",
    "cohens_d",
    "compare_to_benchmark",
    "comprehensive_fairness_test",
    "compute_constraint_violation",
    "compute_disparity_effect_sizes",
    "compute_effect_sizes",
    "compute_feature_correlations",
    "compute_pareto_frontier",
    "compute_proxy_correlations",
    "compute_regression_effect_sizes",
    "compute_robust_metrics",
    "conditional_adverse_impact",
    "conditional_demographic_disparity",
    "conditional_demographic_disparity_with_ci",
    "contingency_test",
    "counterfactual_augment",
    "create_calibration_dashboard",
    "create_calibrator",
    "create_factorial_design",
    "create_fairness_callback",
    "create_fairness_dashboard",
    "create_reweighter",
    "create_threshold_optimizer",
    "demographic_parity_difference",
    "demographic_parity_difference_with_ci",
    "demographic_parity_ratio",
    "detect_historical_patterns",
    "detect_protected_attributes",
    "detect_representation_bias",
    "detect_specification_bias",
    "detect_temporal_drift",
    "discover_intersectional_groups",
    "disparate_impact_ratio",
    "disparate_impact_ratio_with_ci",
    "domain_historical_context",
    "empirical_likelihood_ci",
    "equal_opportunity_difference",
    "equal_opportunity_difference_with_ci",
    "equalized_odds_difference",
    "equalized_odds_difference_with_ci",
    "expected_calibration_error",
    "explain_fairness_report",
    "exposure_parity_difference",
    "exposure_parity_ratio",
    "exposure_parity_rerank",
    "fairness_test",
    "find_feasible_thresholds",
    "find_proxy_chains",
    "fnr_parity_difference",
    "fpr_parity_difference",
    "fpr_parity_difference_with_ci",
    "get_available_styles",
    "get_group_metrics_with_ci",
    "get_group_rankings",
    "get_palettes",
    "get_ranking_group_metrics",
    "group_calibration_metrics",
    "group_reliability",
    "identify_feature_proxies",
    "identify_privileged_groups",
    "identify_proxy_features",
    "identify_proxy_variables",
    "impossibility_diagnostics",
    "integrated_calibration_index",
    "integrated_calibration_index_with_ci",
    "interpret_effect_size",
    "intersectional_disparity_analysis",
    "log_fairness_to_mlflow",
    "log_fairness_to_wandb",
    "mae_parity_difference",
    "mae_parity_difference_with_ci",
    "make_fair_classifier",
    "make_fair_regressor",
    "maximum_calibration_error",
    "mean_prediction_difference",
    "mean_prediction_difference_with_ci",
    "mitigation_pareto",
    "mmd_gaussian",
    "multicalibration",
    "multicalibration_with_ci",
    "multivariate_proxy_leakage",
    "negative_predictive_value_difference",
    "negative_predictive_value_difference_with_ci",
    "net_benefit_parity",
    "noise_floor_from_runs",
    "normalized_discounted_kl_divergence",
    "odds_ratio",
    "parametrize_fairness",
    "permutation_test",
    "permutation_test_demographic_parity",
    "permutation_test_equal_opportunity",
    "plot_calibration_comparison",
    "plot_calibration_disparity",
    "plot_confidence_intervals",
    "plot_effect_sizes",
    "plot_fairness_metrics",
    "plot_fairness_report",
    "plot_group_calibration",
    "plot_group_comparison",
    "plot_group_disparity_heatmap",
    "plot_metrics_radar",
    "plot_reliability_diagram",
    "plot_tradeoff_curve",
    "predictive_parity_difference",
    "predictive_parity_difference_with_ci",
    "preview_palette",
    "pricing_disparity",
    "pricing_disparity_with_ci",
    "print_explanations",
    "print_report",
    "propensity_weights",
    "r2_parity_difference",
    "rank_fairness_issues",
    "recommend_calibration_strategy",
    "regression_fairness_report",
    "reliability_tier",
    "require_checked",
    "residual_bias",
    "risk_ratio",
    "rmse_parity_difference",
    "rmse_parity_difference_with_ci",
    "robust_fairness_comparison",
    "run_disparity_tests",
    "save_fairness_plots",
    "scan_fairness_violations",
    "select_method",
    "selection_rate_disparity_matrix",
    "sensitivity_analysis",
    "sequential_fairness_test",
    "set_branding",
    "simulate_threshold_change",
    "simultaneous_disparity_bounds",
    "status",
    "stratified_bootstrap_ci",
    "stress_test_fairness",
    "subgroup_robustness_audit",
    "test_equalized_odds_chi_square",
    "worst_group_accuracy",
]

# Public subpackages bound as module attributes on import (present in
# dir(vfairness) but not listed in __all__).
EXPECTED_PUBLIC_SUBMODULES = [
    "agents",
    "branding",
    "evaluation",
    "exceptions",
    "explainer",
    "in_processing",
    "llm",
    "multi_agent",
    "net",
    "operations",
    "post_processing",
    "preprocessing",
    "result",
]


def test_all_snapshot_matches():
    current = sorted(v.__all__)
    assert current == EXPECTED_ALL, (
        "vfairness.__all__ changed. If this was intentional, update "
        "EXPECTED_ALL in this test AND add a CHANGELOG.md entry. "
        f"Added: {sorted(set(current) - set(EXPECTED_ALL))}. "
        f"Removed: {sorted(set(EXPECTED_ALL) - set(current))}."
    )


def test_all_has_no_duplicates():
    assert len(v.__all__) == len(set(v.__all__))


def test_every_all_name_is_importable():
    missing = [name for name in v.__all__ if not hasattr(v, name)]
    assert not missing, f"Names in __all__ missing from module: {missing}"


def test_public_submodules_snapshot_matches():
    # Compute the surface in a FRESH interpreter. dir(vfairness) is sensitive to
    # import order: other tests in a full-suite run import optional subpackages
    # (rendering, xai, vision, ...) into the package namespace, which would make
    # this snapshot pass or fail depending on which tests ran first. A clean
    # subprocess sees only the submodules __init__ binds eagerly on import.
    src_dir = os.path.dirname(os.path.dirname(os.path.abspath(v.__file__)))
    code = (
        "import json, vfairness as _v; "
        "print(json.dumps(sorted(n for n in dir(_v) "
        "if not n.startswith('_') and n not in set(_v.__all__))))"
    )
    env = {**os.environ, "PYTHONPATH": src_dir + os.pathsep + os.environ.get("PYTHONPATH", "")}
    res = subprocess.run([sys.executable, "-c", code], capture_output=True, text=True, env=env)
    assert res.returncode == 0, f"subprocess failed:\n{res.stderr}"
    current = json.loads(res.stdout.strip().splitlines()[-1])
    assert current == EXPECTED_PUBLIC_SUBMODULES, (
        "Public dir(vfairness) surface (beyond __all__) changed. If this was "
        "intentional, update EXPECTED_PUBLIC_SUBMODULES AND add a CHANGELOG.md "
        f"entry. Added: {sorted(set(current) - set(EXPECTED_PUBLIC_SUBMODULES))}. "
        f"Removed: {sorted(set(EXPECTED_PUBLIC_SUBMODULES) - set(current))}."
    )
