"""
vfairness Beta Go-Live proof ledger.

WHAT THIS IS. For every capability in ``CAPABILITY_REGISTRY``, this file records
how far its **honesty** has actually been proved: not whether it computes a
number, but whether it refuses to invent one when nothing is measurable.

WHY IT EXISTS. The library's one standing rule is THREE STATES, NEVER TWO:
measured / failed / could-not-check. A capability that quietly substitutes a
neutral default (0.0, 1.0, ``True``, ``"pass"``) for a value nobody measured
reads, to every downstream grader, chart and report, exactly like a measurement.
Before the 0.1.0 beta we measured the whole surface for that defect. This ledger
is the result, and it is deliberately written so that a capability nobody has
checked CANNOT look like one that passed.

The ledger is the same shape as the thing it audits. A capability with no
evidence is ``BGL-C UNPROVEN``. It is never silently promoted, and there is no
default value: ``scripts/beta_go_live_ledger.py`` fails closed, and
``tests/test_beta_go_live_proof_ledger.py`` refuses any entry whose claim is not
backed by a file that exists.

HOW IT WAS MEASURED. A harness executed every registered capability twice: once
on HEALTHY input carrying a real, findable group disparity, and once on each
degenerate input where the thing it claims to measure does not exist at all
(one group only; every label identical; every score NaN; zero rows; every score
identical so no ranking exists; two rows; a group with a single row; text with
no lexicon word in it). Any capability that answered confidently in the second
case went to an independent judge, then to an adversarial verifier told to
refute the judge, then to a third pass whose only job was to re-run the claim at
the PUBLIC entry point and report the real returned value. Only findings that
survived all three are recorded as defects here.

Full method, batch definitions and the summary table: docs/BETA_GO_LIVE_PLAN.md
"""

from __future__ import annotations

from typing import TypedDict


class ProofBatch(TypedDict):
    """Definition of one rung on the proof ladder."""

    label: str  # short human name
    means: str  # what a reader may conclude
    requires: str  # what a capability must satisfy to be in this batch
    may_not_conclude: str  # what this batch explicitly does NOT establish


class ProofRecord(TypedDict):
    """Proof status of a single registered capability."""

    batch: str  # one of PROOF_BATCHES
    shared_with: list  # other dispatch keys resolving to the SAME live object
    reached: bool  # was it executed on degenerate input at all
    judged: int  # entry points independently adjudicated
    open_defects: int  # confirmed, three-pass-verified fabrications still open
    severities: list  # severities of those open defects
    pins: list  # test files pinning its could-not-check path
    fix_minutes: int  # estimated minutes to close open_defects (0 if none)


# The date the surface was measured. Every claim in CAPABILITY_PROOF is a claim
# about the code as of this date; re-run scripts/beta_go_live_ledger.py after any
# change to a registered capability.
MEASURED_ON = "2026-09-11"
MEASURED_AT_COMMIT = "8559dda"

# ``COUNTS_AS_OF`` is emitted below by the generator and is a DIFFERENT date from
# ``MEASURED_ON``. The census reproduced 157 defects; what the batches show is
# what remains after the fix waves since. Anything rendering these counts must
# date them with COUNTS_AS_OF, not with MEASURED_ON: a surface that shows a
# count beside the census date tells a reader the census found that count, and
# both halves of that sentence are true while the sentence is false. Found twice
# in one day, once here and once on the platform's coverage card.

PROOF_BATCHES: dict[str, ProofBatch] = {
    "BGL-A": {
        "label": "PROVEN",
        "means": (
            "Executed on healthy input and on the degenerate inputs relevant to "
            "what it claims to measure. In each of those it EITHER refused "
            "(returned NaN, None, an explicit could-not-check, or raised) OR "
            "returned a value an independent judge showed to be a true "
            "measurement for that input. Nothing it returned survived three "
            "passes as a fabrication, and at least one test in the suite names "
            "it next to a refusal assertion."
        ),
        "requires": (
            "reached=True AND judged>=1 AND open_defects==0 AND at least one test "
            "file, present in the repository, that names the capability within "
            "twenty lines of a refusal assertion."
        ),
        "may_not_conclude": (
            "Three things, each of which stays open at 0.1.0. (1) That the NUMBER "
            "it returns on healthy data is statistically correct: this ladder "
            "measures honesty about the ABSENCE of a measurement, not the accuracy "
            "of one. (2) That the pin covers every degenerate scenario: the pin "
            "test is a proximity match, so it proves a refusal is asserted "
            "somewhere near this capability, not that THIS scenario is the one "
            "asserted. (3) That the pin has been sabotage-checked. A guard that "
            "cannot fail looks identical to one that passed, and only a reinstated "
            "defect tells them apart. Promoting BGL-A to a sabotage-verified rung "
            "is the exit criterion of Stage 4 in docs/BETA_GO_LIVE_PLAN.md."
        ),
    },
    "BGL-B": {
        "label": "SEMI-PROVEN",
        "means": (
            "Executed on healthy and degenerate input and judged clean today, but "
            "nothing in the suite holds it there. The behaviour is observed, not "
            "protected: the next refactor can reintroduce the defect and every "
            "gate will stay green."
        ),
        "requires": (
            "reached (generically, or by a hand-written fixture) AND judged>=1 AND "
            "open_defects==0 AND no test file names it near a refusal assertion."
        ),
        "may_not_conclude": (
            "That it will still be honest after the next change. A BGL-B capability "
            "is one commit away from BGL-D with no alarm."
        ),
    },
    "BGL-C": {
        "label": "UNPROVEN",
        "means": (
            "No execution evidence on degenerate input. Either no fixture could be "
            "constructed generically, or it needs a collaborator (a live LLM proxy, "
            "a fitted pipeline, a torch model) the harness does not have. Its "
            "honesty is UNKNOWN, which is not the same as suspect and is emphatically "
            "not the same as clean."
        ),
        "requires": "no adjudicated execution on degenerate input.",
        "may_not_conclude": (
            "Anything at all about whether it fabricates. This batch exists so that "
            "'not checked' can never be read as 'checked and fine'."
        ),
    },
    "BGL-D": {
        "label": "DEFECT OPEN",
        "means": (
            "At least one entry point was proved, by three independent passes ending "
            "in a re-run at the public API, to hand back a confident value where "
            "nothing was measurable. The capability still computes correctly on "
            "healthy data; what is broken is what it says when it cannot."
        ),
        "requires": "open_defects>=1, each reproduced at the public entry point.",
        "may_not_conclude": (
            "That the capability is unusable. It means its could-not-check path is "
            "wrong, and a caller who hits that path is told a number that was never "
            "measured."
        ),
    },
}


PROOF_BLOCK_BEGIN = "Beta Go-Live proof status"
PROOF_BLOCK_END = "(end Beta Go-Live proof status)"


def strip_proof_block(doc: str | None) -> str:
    """Return ``doc`` without its generated Beta Go-Live block.

    Anything that PARSES a docstring must strip this block first, because the
    block is machine-written prose that can collide with a heuristic aimed at
    human prose. That is not hypothetical: ``tests/test_docs_truth.py`` detects a
    paper citation with ``\\b(19|20)\\d\\d\\b``, and the stamp's own date,
    ``(2026-09-11)``, matched it. Every stamped metric suddenly "cited a paper"
    and was required to carry a divergence note.

    The right fix was not to weaken the citation rule, which would let a real
    citation slip past, nor to disguise the date, which a reader needs. It was to
    take the generated block out of the text a prose heuristic reads.
    """
    if not doc:
        return ""
    start = doc.find(PROOF_BLOCK_BEGIN)
    if start < 0:
        return doc
    end = doc.find(PROOF_BLOCK_END, start)
    if end < 0:
        return doc[:start].rstrip() + "\n"
    return (
        doc[:start].rstrip() + "\n" + doc[end + len(PROOF_BLOCK_END) :].lstrip("\n")
    ).rstrip() + "\n"


#: The date the counts below are true for. NOT ``MEASURED_ON``.
COUNTS_AS_OF = "2026-09-17"

# Generated by scripts/beta_go_live_ledger.py from
# docs/beta-go-live-census-2026-09-11.json. Do not hand-edit:
# change the evidence and regenerate, so the claim and the record cannot drift.
CAPABILITY_PROOF: dict[str, ProofRecord] = {
    "accuracy_parity_difference": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": ["tests/test_assessability_chain.py"],
        "fix_minutes": 0,
    },
    "action_bias_analyzer": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": [
            "tests/test_agents.py",
            "tests/test_no_aggregator_fabricates_a_verdict.py",
            "tests/test_readiness4_agents.py",
            "tests/test_readiness5_probe5.py",
            "tests/test_readiness6_manufactured.py",
        ],
        "fix_minutes": 0,
    },
    "adaptive_threshold_management": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": ["tests/test_readiness6_detection.py"],
        "fix_minutes": 0,
    },
    "adasyn": {
        "batch": "BGL-B",
        "shared_with": [],
        "reached": True,
        "judged": 4,
        "open_defects": 0,
        "severities": [],
        "pins": [],
        "fix_minutes": 0,
    },
    "adversarial_collusion_detector": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": [
            "tests/test_no_aggregator_fabricates_a_verdict.py",
            "tests/test_readiness6_agents.py",
        ],
        "fix_minutes": 0,
    },
    "adversarial_debiasing": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 3,
        "open_defects": 0,
        "severities": [],
        "pins": ["tests/test_audit_wave6_adversarial.py"],
        "fix_minutes": 0,
    },
    "alert_prioritization": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": [
            "tests/test_no_aggregator_fabricates_a_verdict.py",
            "tests/test_readiness6_detection.py",
        ],
        "fix_minutes": 0,
    },
    "analyze_statistical_disparities": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 3,
        "open_defects": 0,
        "severities": [],
        "pins": ["tests/test_readiness4_docs4.py"],
        "fix_minutes": 0,
    },
    "anchors": {
        "batch": "BGL-B",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": [],
        "fix_minutes": 0,
    },
    "attention_weighted_rank_fairness": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": ["tests/test_assessability_chain.py", "tests/test_ranking.py"],
        "fix_minutes": 0,
    },
    "auroc_parity": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": [
            "tests/test_audit_wave6_calibration.py",
            "tests/test_audit_wave6_gate_report.py",
            "tests/test_readiness4_metrics.py",
            "tests/test_spine_classification_metrics.py",
        ],
        "fix_minutes": 0,
    },
    "auto_discovery": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": [
            "tests/test_no_aggregator_fabricates_a_verdict.py",
            "tests/test_readiness_discovery.py",
        ],
        "fix_minutes": 0,
    },
    "bayesian_proportion_ci": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": ["tests/test_audit_wave2.py", "tests/test_readiness4_docs4.py"],
        "fix_minutes": 0,
    },
    "benchmark_runner": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": [
            "tests/test_no_aggregator_fabricates_a_verdict.py",
            "tests/test_readiness6_textmatch.py",
            "tests/test_readiness_llmoutage.py",
        ],
        "fix_minutes": 0,
    },
    "benjamini_hochberg_correction": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": ["tests/test_audit_wave5_hardening.py", "tests/test_readiness6_metrics.py"],
        "fix_minutes": 0,
    },
    "beta_calibration": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 3,
        "open_defects": 0,
        "severities": [],
        "pins": ["tests/test_no_aggregator_fabricates_a_verdict.py"],
        "fix_minutes": 0,
    },
    "bias_audit": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": [
            "tests/test_audit6_wave4_g_mcp_regulatory.py",
            "tests/test_no_aggregator_fabricates_a_verdict.py",
            "tests/test_pulse_traces.py",
            "tests/test_readiness2_benchmarks.py",
            "tests/test_readiness4_nan1.py",
            "tests/test_readiness4_pulse.py",
            "tests/test_readiness6_agents.py",
            "tests/test_readiness6_textmatch.py",
        ],
        "fix_minutes": 0,
    },
    "bias_monitor": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": ["tests/test_audit_wave6_cicd_nan.py", "tests/test_readiness6_gates.py"],
        "fix_minutes": 0,
    },
    "bonferroni_correction": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": ["tests/test_audit_wave5_hardening.py"],
        "fix_minutes": 0,
    },
    "bootstrap_ci": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": [
            "tests/test_audit_wave5_hardening.py",
            "tests/test_audit_wave6_statistics.py",
            "tests/test_no_aggregator_fabricates_a_verdict.py",
            "tests/test_parameter_boundary_refusals.py",
            "tests/test_statistics.py",
        ],
        "fix_minutes": 0,
    },
    "bounded_group_loss": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": ["tests/test_readiness2_inert.py"],
        "fix_minutes": 0,
    },
    "bounded_group_loss_constraint": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 3,
        "open_defects": 0,
        "severities": [],
        "pins": ["tests/test_readiness2_inert.py"],
        "fix_minutes": 0,
    },
    "brier_score": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": ["tests/test_audit_wave4_postproc.py"],
        "fix_minutes": 0,
    },
    "brier_score_decomposition": {
        "batch": "BGL-B",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": [],
        "fix_minutes": 0,
    },
    "calibrated_equalization": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 4,
        "open_defects": 0,
        "severities": [],
        "pins": [
            "tests/test_audit6_lane3_post_in_processing.py",
            "tests/test_audit6_wave2_argument_order.py",
            "tests/test_audit6_wave2_constraint.py",
            "tests/test_audit_wave2.py",
        ],
        "fix_minutes": 0,
    },
    "calibration": {
        "batch": "BGL-A",
        "shared_with": ["calibration_analysis"],
        "reached": True,
        "judged": 8,
        "open_defects": 0,
        "severities": [],
        "pins": [
            "tests/test_adapters_last_four.py",
            "tests/test_audit6_lane3_post_in_processing.py",
            "tests/test_readiness2_explainer.py",
        ],
        "fix_minutes": 0,
    },
    "calibration_analysis": {
        "batch": "BGL-A",
        "shared_with": ["calibration"],
        "reached": True,
        "judged": 8,
        "open_defects": 0,
        "severities": [],
        "pins": [
            "tests/test_adapters_last_four.py",
            "tests/test_audit6_lane3_post_in_processing.py",
            "tests/test_readiness2_explainer.py",
        ],
        "fix_minutes": 0,
    },
    "calibration_curve": {
        "batch": "BGL-B",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": [],
        "fix_minutes": 0,
    },
    "calibration_difference": {
        "batch": "BGL-A",
        "shared_with": ["calibration_disparity"],
        "reached": True,
        "judged": 4,
        "open_defects": 0,
        "severities": [],
        "pins": [
            "tests/test_adapters_calibration_verdicts.py",
            "tests/test_audit6_lane3_post_in_processing.py",
            "tests/test_audit_wave4_postproc.py",
            "tests/test_desc_agrees_with_canvas.py",
            "tests/test_gate_direction.py",
            "tests/test_no_aggregator_fabricates_a_verdict.py",
            "tests/test_pulse_deferred_tail.py",
        ],
        "fix_minutes": 0,
    },
    "calibration_disparity": {
        "batch": "BGL-A",
        "shared_with": ["calibration_difference"],
        "reached": True,
        "judged": 4,
        "open_defects": 0,
        "severities": [],
        "pins": [
            "tests/test_adapters_calibration_verdicts.py",
            "tests/test_audit6_lane3_post_in_processing.py",
            "tests/test_audit_wave4_postproc.py",
            "tests/test_desc_agrees_with_canvas.py",
            "tests/test_gate_direction.py",
            "tests/test_no_aggregator_fabricates_a_verdict.py",
            "tests/test_pulse_deferred_tail.py",
        ],
        "fix_minutes": 0,
    },
    "calibration_in_the_large": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": ["tests/test_audit_wave6_calibration.py"],
        "fix_minutes": 0,
    },
    "calibration_slope": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": ["tests/test_assert_fairness_fail_closed.py", "tests/test_audit_wave4_postproc.py"],
        "fix_minutes": 0,
    },
    "causal_fairness": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": ["tests/test_audit6_lane3_post_in_processing.py"],
        "fix_minutes": 0,
    },
    "causal_fairness_graph": {
        "batch": "BGL-B",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": [],
        "fix_minutes": 0,
    },
    "check_model_card": {
        "batch": "BGL-B",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": [],
        "fix_minutes": 0,
    },
    "classification_fairness_report": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": [
            "tests/test_assessability_chain.py",
            "tests/test_audit6_wave4_e_statistics.py",
            "tests/test_audit_wave1.py",
            "tests/test_audit_wave6_gate_report.py",
            "tests/test_gate_nan_fail_closed.py",
            "tests/test_ratio_null_and_degenerate.py",
            "tests/test_readiness4_docs4.py",
            "tests/test_readiness4_metrics.py",
            "tests/test_readiness6_metrics.py",
            "tests/test_rendering_assessable.py",
            "tests/test_report_provenance.py",
            "tests/test_report_verdict_direction.py",
        ],
        "fix_minutes": 0,
    },
    "compositionality_analyzer": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": ["tests/test_no_aggregator_fabricates_a_verdict.py"],
        "fix_minutes": 0,
    },
    "compute_effect_sizes": {
        "batch": "BGL-B",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": [],
        "fix_minutes": 0,
    },
    "compute_feature_correlations": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": [
            "tests/test_audit6_lane2_feature_engineering.py",
            "tests/test_bgl_final_audit_repairs.py",
            "tests/test_site_api_reference_calls_resolve.py",
        ],
        "fix_minutes": 0,
    },
    "conditional_adverse_impact": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": [
            "tests/test_audit_wave6_regression_controls.py",
            "tests/test_spine_continuous_metrics.py",
        ],
        "fix_minutes": 0,
    },
    "conditional_demographic_disparity": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": ["tests/test_docs_truth.py", "tests/test_spine_classification_metrics.py"],
        "fix_minutes": 0,
    },
    "conditional_demographic_disparity_with_ci": {
        "batch": "BGL-B",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": [],
        "fix_minutes": 0,
    },
    "conditional_independence_regularizer": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": ["tests/test_audit6_lane3_post_in_processing.py"],
        "fix_minutes": 0,
    },
    "constraint_grid_search": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": [
            "tests/test_audit6_lane3_post_in_processing.py",
            "tests/test_no_aggregator_fabricates_a_verdict.py",
        ],
        "fix_minutes": 0,
    },
    "correlation_penalty": {
        "batch": "BGL-B",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": [],
        "fix_minutes": 0,
    },
    "correlation_reduction": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": [
            "tests/test_audit3_preproc_encoding.py",
            "tests/test_audit6_lane2_feature_engineering.py",
        ],
        "fix_minutes": 0,
    },
    "correspondence_tester": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": ["tests/test_readiness4_agents.py"],
        "fix_minutes": 0,
    },
    "cot_faithfulness_analyzer": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": ["tests/test_readiness6_textmatch.py"],
        "fix_minutes": 0,
    },
    "counterfactual_augment": {
        "batch": "BGL-B",
        "shared_with": [],
        "reached": True,
        "judged": 4,
        "open_defects": 0,
        "severities": [],
        "pins": [],
        "fix_minutes": 0,
    },
    "counterfactual_fairness": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": ["tests/test_audit6_lane3_post_in_processing.py"],
        "fix_minutes": 0,
    },
    "counterfactual_fairness_metric": {
        "batch": "BGL-B",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": [],
        "fix_minutes": 0,
    },
    "counterfactual_tester": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": [
            "tests/test_llm_wave0_honesty.py",
            "tests/test_readiness2_docs2.py",
            "tests/test_readiness6_agents.py",
        ],
        "fix_minutes": 0,
    },
    "create_calibrator": {
        "batch": "BGL-B",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": [],
        "fix_minutes": 0,
    },
    "create_constraint": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": ["tests/test_readiness2_inert.py"],
        "fix_minutes": 0,
    },
    "create_fairness_loss": {
        "batch": "BGL-B",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": [],
        "fix_minutes": 0,
    },
    "create_reweighter": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": [
            "tests/test_audit6_wave2_constraint.py",
            "tests/test_bgl_final_d01.py",
            "tests/test_bgl_stage2_s2g05.py",
        ],
        "fix_minutes": 0,
    },
    "create_threshold_optimizer": {
        "batch": "BGL-B",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": [],
        "fix_minutes": 0,
    },
    "data_bias_validation": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": [
            "tests/test_audit6_lane1_reporting.py",
            "tests/test_readiness6_gates.py",
            "tests/test_rowlevel_validator_reporting.py",
        ],
        "fix_minutes": 0,
    },
    "decoding_trust_runner": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": [
            "tests/test_decodingtrust_provenance.py",
            "tests/test_readiness6_verdicts.py",
            "tests/test_readiness_llmoutage.py",
        ],
        "fix_minutes": 0,
    },
    "decompose_mediation": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": ["tests/test_registry_completeness.py"],
        "fix_minutes": 0,
    },
    "delegation_routing_auditor": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": ["tests/test_audit_wave5_agentsmisc.py", "tests/test_readiness6_agents.py"],
        "fix_minutes": 0,
    },
    "demographic_parity_constraint": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 3,
        "open_defects": 0,
        "severities": [],
        "pins": ["tests/test_readiness2_inert.py", "tests/test_readiness_docs.py"],
        "fix_minutes": 0,
    },
    "demographic_parity_difference": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": [
            "tests/test_assert_fairness_fail_closed.py",
            "tests/test_assert_fairness_fail_closed_status.py",
            "tests/test_assessability_chain.py",
            "tests/test_audit6_lane4_evaluation.py",
            "tests/test_audit6_wave4_d_integrations.py",
            "tests/test_audit6_wave4_e_statistics.py",
            "tests/test_audit_wave1.py",
            "tests/test_audit_wave4_evalmetrics.py",
            "tests/test_audit_wave4_ops.py",
            "tests/test_audit_wave5_hardening.py",
            "tests/test_audit_wave6_cicd_nan.py",
            "tests/test_audit_wave6_gate_report.py",
            "tests/test_classification.py",
            "tests/test_compliance_three_state.py",
            "tests/test_desc_agrees_with_canvas.py",
            "tests/test_detailed_report_direction.py",
            "tests/test_explainer_direction.py",
            "tests/test_gate_nan_fail_closed.py",
            "tests/test_integrations_none_score.py",
            "tests/test_metric_direction.py",
            "tests/test_monitoring_nan_not_measured.py",
            "tests/test_no_aggregator_fabricates_a_verdict.py",
            "tests/test_no_telemetry.py",
            "tests/test_parameter_boundary_refusals.py",
            "tests/test_pattern_core_adapters.py",
            "tests/test_perf_scale.py",
            "tests/test_property_invariants.py",
            "tests/test_ratio_null_and_degenerate.py",
            "tests/test_readiness2_docs2.py",
            "tests/test_readiness2_headline.py",
            "tests/test_readiness4_docs4.py",
            "tests/test_readiness5_gate.py",
            "tests/test_readiness6_dashboard.py",
            "tests/test_readiness6_gates.py",
            "tests/test_readiness6_infinity.py",
            "tests/test_readiness6_metrics.py",
            "tests/test_readiness_docs.py",
            "tests/test_readiness_reports.py",
            "tests/test_rendering_assessable.py",
            "tests/test_rendering_direction.py",
            "tests/test_report_verdict_direction.py",
            "tests/test_reporting_direction.py",
            "tests/test_risk_register_scoring.py",
            "tests/test_rowlevel_fairness_cicd.py",
            "tests/test_rowlevel_validator_reporting.py",
            "tests/test_streaming.py",
            "tests/test_task_type_detection.py",
            "tests/test_validation_fail_closed.py",
            "tests/test_verdict_defaults.py",
            "tests/test_visualization_direction.py",
        ],
        "fix_minutes": 0,
    },
    "demographic_parity_difference_with_ci": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": [
            "tests/test_audit6_wave4_e_statistics.py",
            "tests/test_audit_wave4_evalmetrics.py",
            "tests/test_no_telemetry.py",
            "tests/test_parameter_boundary_refusals.py",
            "tests/test_readiness_docs.py",
        ],
        "fix_minutes": 0,
    },
    "demographic_parity_loss": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": ["tests/test_audit_wave5_inproc.py"],
        "fix_minutes": 0,
    },
    "demographic_parity_ratio": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": [
            "tests/test_assessability_chain.py",
            "tests/test_audit6_wave4_d_integrations.py",
            "tests/test_audit6_wave4_e_statistics.py",
            "tests/test_audit_wave5_hardening.py",
            "tests/test_explainer_direction.py",
            "tests/test_gate_nan_fail_closed.py",
            "tests/test_metric_direction.py",
            "tests/test_no_telemetry.py",
            "tests/test_perf_scale.py",
            "tests/test_property_invariants.py",
            "tests/test_ratio_null_and_degenerate.py",
            "tests/test_readiness4_docs4.py",
            "tests/test_readiness6_gates.py",
            "tests/test_readiness6_metrics.py",
            "tests/test_rendering_assessable.py",
            "tests/test_rendering_direction.py",
            "tests/test_report_verdict_direction.py",
            "tests/test_reporting_direction.py",
            "tests/test_task_type_detection.py",
        ],
        "fix_minutes": 0,
    },
    "detect_historical_patterns": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": ["tests/test_readiness6_names.py"],
        "fix_minutes": 0,
    },
    "detect_protected_attributes": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": ["tests/test_readiness_tracker.py"],
        "fix_minutes": 0,
    },
    "detect_representation_bias": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": [
            "tests/test_audit6_wave3_s01_representation.py",
            "tests/test_bias_audit_representation.py",
            "tests/test_readiness2_benchmarks.py",
            "tests/test_readiness2_docs2.py",
            "tests/test_readiness3_repr2.py",
        ],
        "fix_minutes": 0,
    },
    "dice_counterfactuals": {
        "batch": "BGL-B",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": [],
        "fix_minutes": 0,
    },
    "discover_intersectional_groups": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": ["tests/test_audit6_lane4_evaluation.py", "tests/test_readiness_discovery.py"],
        "fix_minutes": 0,
    },
    "disparate_impact_ratio": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": [
            "tests/test_assessability_chain.py",
            "tests/test_audit3_ratio_sweep.py",
            "tests/test_audit_wave4_postproc.py",
            "tests/test_audit_wave6_statistics.py",
            "tests/test_compliance_three_state.py",
            "tests/test_detailed_report_direction.py",
            "tests/test_explainer_direction.py",
            "tests/test_metric_direction.py",
            "tests/test_property_invariants.py",
            "tests/test_ratio_null_and_degenerate.py",
            "tests/test_readiness2_headline.py",
            "tests/test_readiness5_gate.py",
            "tests/test_readiness6_direction.py",
            "tests/test_readiness6_gates.py",
            "tests/test_readiness6_infinity.py",
            "tests/test_readiness6_metrics.py",
            "tests/test_rendering_direction.py",
            "tests/test_report_verdict_direction.py",
            "tests/test_reporting_direction.py",
            "tests/test_spine_classification_metrics.py",
            "tests/test_verdict_defaults.py",
            "tests/test_visualization_direction.py",
        ],
        "fix_minutes": 0,
    },
    "disparate_impact_ratio_with_ci": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": [
            "tests/test_audit_wave6_statistics.py",
            "tests/test_metric_direction.py",
            "tests/test_ratio_null_and_degenerate.py",
        ],
        "fix_minutes": 0,
    },
    "disparate_impact_removal": {
        "batch": "BGL-B",
        "shared_with": [],
        "reached": True,
        "judged": 3,
        "open_defects": 0,
        "severities": [],
        "pins": [],
        "fix_minutes": 0,
    },
    "distribution_matching": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 4,
        "open_defects": 0,
        "severities": [],
        "pins": [
            "tests/test_audit6_lane3_post_in_processing.py",
            "tests/test_audit6_wave2_argument_order.py",
            "tests/test_audit6_wave2_constraint.py",
            "tests/test_audit_wave2.py",
        ],
        "fix_minutes": 0,
    },
    "drift_detection": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": [
            "tests/test_no_aggregator_fabricates_a_verdict.py",
            "tests/test_readiness2_explainer.py",
            "tests/test_readiness5_store5.py",
            "tests/test_readiness6_detection.py",
            "tests/test_readiness6_manufactured.py",
            "tests/test_readiness_reports.py",
        ],
        "fix_minutes": 0,
    },
    "embedding_bias_detector": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": ["tests/test_readiness6_agents.py"],
        "fix_minutes": 0,
    },
    "emergent_bias_detector": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": [
            "tests/test_no_aggregator_fabricates_a_verdict.py",
            "tests/test_pulse_traces.py",
            "tests/test_readiness4_nan1.py",
            "tests/test_readiness4_pulse.py",
            "tests/test_readiness6_agents.py",
        ],
        "fix_minutes": 0,
    },
    "equal_opportunity_constraint": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 3,
        "open_defects": 0,
        "severities": [],
        "pins": [
            "tests/test_audit3_inproc_constraints.py",
            "tests/test_equalized_odds_unmeasurable_arm.py",
        ],
        "fix_minutes": 0,
    },
    "equal_opportunity_difference": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": [
            "tests/test_assert_fairness_fail_closed.py",
            "tests/test_assert_fairness_fail_closed_status.py",
            "tests/test_assessability_chain.py",
            "tests/test_audit6_wave4_d_integrations.py",
            "tests/test_audit_wave4_evalmetrics.py",
            "tests/test_audit_wave6_metrics.py",
            "tests/test_equalized_odds_unmeasurable_arm.py",
            "tests/test_explainer_direction.py",
            "tests/test_gate_nan_fail_closed.py",
            "tests/test_perf_scale.py",
            "tests/test_property_invariants.py",
            "tests/test_readiness2_headline.py",
            "tests/test_readiness4_metrics.py",
            "tests/test_readiness6_metrics.py",
            "tests/test_rendering_assessable.py",
            "tests/test_rowlevel_validator_reporting.py",
            "tests/test_task_type_detection.py",
        ],
        "fix_minutes": 0,
    },
    "equal_opportunity_difference_with_ci": {
        "batch": "BGL-B",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": [],
        "fix_minutes": 0,
    },
    "equal_opportunity_loss": {
        "batch": "BGL-B",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": [],
        "fix_minutes": 0,
    },
    "equalized_odds_constraint": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 3,
        "open_defects": 0,
        "severities": [],
        "pins": [
            "tests/test_audit3_inproc_constraints.py",
            "tests/test_equalized_odds_unmeasurable_arm.py",
            "tests/test_no_aggregator_fabricates_a_verdict.py",
            "tests/test_readiness4_constraints.py",
        ],
        "fix_minutes": 0,
    },
    "equalized_odds_difference": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": [
            "tests/test_assessability_chain.py",
            "tests/test_audit6_wave4_d_integrations.py",
            "tests/test_audit_final_release.py",
            "tests/test_audit_wave4_evalmetrics.py",
            "tests/test_audit_wave4_ops.py",
            "tests/test_audit_wave5_hardening.py",
            "tests/test_audit_wave6_cicd_nan.py",
            "tests/test_audit_wave6_gate_report.py",
            "tests/test_audit_wave6_metrics.py",
            "tests/test_equalized_odds_unmeasurable_arm.py",
            "tests/test_no_aggregator_fabricates_a_verdict.py",
            "tests/test_no_telemetry.py",
            "tests/test_perf_scale.py",
            "tests/test_readiness2_headline.py",
            "tests/test_readiness4_docs4.py",
            "tests/test_readiness4_metrics.py",
            "tests/test_readiness6_gates.py",
            "tests/test_readiness6_metrics.py",
            "tests/test_rendering_assessable.py",
            "tests/test_rowlevel_fairness_cicd.py",
            "tests/test_task_type_detection.py",
            "tests/test_visualization_direction.py",
        ],
        "fix_minutes": 0,
    },
    "equalized_odds_difference_with_ci": {
        "batch": "BGL-B",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": [],
        "fix_minutes": 0,
    },
    "equalized_odds_loss": {
        "batch": "BGL-B",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": [],
        "fix_minutes": 0,
    },
    "expected_calibration_error": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": [
            "tests/test_audit_wave4_postproc.py",
            "tests/test_no_telemetry.py",
            "tests/test_property_invariants.py",
        ],
        "fix_minutes": 0,
    },
    "experiment_analysis": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": [
            "tests/test_audit6_lane4_evaluation.py",
            "tests/test_readiness3_recollapse.py",
            "tests/test_readiness6_agents.py",
            "tests/test_readiness6_verdicts.py",
        ],
        "fix_minutes": 0,
    },
    "explanation_diagnostics": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": [
            "tests/test_readiness5_consumers5.py",
            "tests/unit/test_explanation_diagnostics.py",
        ],
        "fix_minutes": 0,
    },
    "exponentiated_gradient": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": [
            "tests/test_audit6_wave4_b_in_processing.py",
            "tests/test_audit_wave5_inproc.py",
            "tests/test_no_aggregator_fabricates_a_verdict.py",
            "tests/test_readiness_docs.py",
            "tests/test_site_api_reference_calls_resolve.py",
        ],
        "fix_minutes": 0,
    },
    "exposure_parity_difference": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": [
            "tests/test_assessability_chain.py",
            "tests/test_parameter_boundary_refusals.py",
            "tests/test_ranking.py",
            "tests/test_rerank_exposure_parity.py",
        ],
        "fix_minutes": 0,
    },
    "exposure_parity_ratio": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": [
            "tests/test_adapters_ranking_verdicts.py",
            "tests/test_assessability_chain.py",
            "tests/test_audit6_wave2_criticals.py",
            "tests/test_audit_wave4_postproc.py",
            "tests/test_explain_matches_canvas.py",
            "tests/test_ranking.py",
        ],
        "fix_minutes": 0,
    },
    "fair_classifier": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 5,
        "open_defects": 0,
        "severities": [],
        "pins": ["tests/test_readiness3_annotations.py", "tests/test_readiness4_constraints.py"],
        "fix_minutes": 0,
    },
    "fair_explainer": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": [
            "tests/test_audit3_ratio_sweep.py",
            "tests/test_audit6_wave4_e_statistics.py",
            "tests/test_no_aggregator_fabricates_a_verdict.py",
            "tests/test_report_verdict_direction.py",
        ],
        "fix_minutes": 0,
    },
    "fair_regressor": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 3,
        "open_defects": 0,
        "severities": [],
        "pins": [
            "tests/test_audit_wave1.py",
            "tests/test_audit_wave6_reductions.py",
            "tests/test_readiness2_docs2.py",
            "tests/test_readiness3_annotations.py",
        ],
        "fix_minutes": 0,
    },
    "fair_representation": {
        "batch": "BGL-B",
        "shared_with": [],
        "reached": True,
        "judged": 4,
        "open_defects": 0,
        "severities": [],
        "pins": [],
        "fix_minutes": 0,
    },
    "fair_representation_loss": {
        "batch": "BGL-B",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": [],
        "fix_minutes": 0,
    },
    "fairness_analysis": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": [
            "tests/test_analyzer_provenance.py",
            "tests/test_api_reference_page_truth.py",
            "tests/test_assessability_chain.py",
            "tests/test_audit6_wave4_d_integrations.py",
            "tests/test_audit_wave4_evalmetrics.py",
            "tests/test_gate_nan_fail_closed.py",
            "tests/test_no_aggregator_fabricates_a_verdict.py",
            "tests/test_no_telemetry.py",
            "tests/test_parameter_boundary_refusals.py",
            "tests/test_perf_scale.py",
            "tests/test_readiness2_headline.py",
            "tests/test_readiness5_store5.py",
            "tests/test_readiness6_agents.py",
            "tests/test_readiness6_direction.py",
            "tests/test_readiness6_gates.py",
            "tests/test_report_provenance.py",
            "tests/test_task_type_detection.py",
            "tests/test_validation_fail_closed.py",
            "tests/test_verdict_defaults.py",
        ],
        "fix_minutes": 0,
    },
    "fairness_aware_bce": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": [
            "tests/test_audit6_lane3_post_in_processing.py",
            "tests/test_audit6_wave4_b_in_processing.py",
        ],
        "fix_minutes": 0,
    },
    "fairness_dashboard": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": ["tests/test_readiness6_dashboard.py", "tests/test_readiness6_direction.py"],
        "fix_minutes": 0,
    },
    "fairness_decomposition": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": [
            "tests/test_readiness6_claims.py",
            "tests/test_readiness6_metrics.py",
            "tests/xai/test_decomposition.py",
        ],
        "fix_minutes": 0,
    },
    "fairness_experiment": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": [
            "tests/test_readiness2_threestate.py",
            "tests/test_readiness3_recollapse.py",
            "tests/test_readiness6_agents.py",
            "tests/test_readiness6_manufactured.py",
            "tests/test_readiness6_verdicts.py",
        ],
        "fix_minutes": 0,
    },
    "fairness_explainer": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": [
            "tests/test_readiness2_docs2.py",
            "tests/test_readiness2_explainer.py",
            "tests/unit/test_explainer.py",
        ],
        "fix_minutes": 0,
    },
    "fairness_gate": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": [
            "tests/test_audit_wave4_ops.py",
            "tests/test_audit_wave6_cicd_nan.py",
            "tests/test_audit_wave6_gate_report.py",
            "tests/test_gate_direction.py",
            "tests/test_gate_four_fifths_reachable.py",
            "tests/test_metric_direction.py",
            "tests/test_no_aggregator_fabricates_a_verdict.py",
            "tests/test_readiness2_headline.py",
            "tests/test_readiness5_gate.py",
            "tests/test_readiness6_gates.py",
            "tests/test_readiness6_infinity.py",
            "tests/test_readiness_docs.py",
        ],
        "fix_minutes": 0,
    },
    "fairness_monitor": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 4,
        "open_defects": 0,
        "severities": [],
        "pins": [
            "tests/test_audit6_lane1_reporting.py",
            "tests/test_no_aggregator_fabricates_a_verdict.py",
            "tests/test_readiness5_consumers5.py",
            "tests/test_readiness5_store5.py",
            "tests/test_readiness_tracker.py",
        ],
        "fix_minutes": 0,
    },
    "fairness_regularization": {
        "batch": "BGL-B",
        "shared_with": ["group_fairness_regularizer"],
        "reached": True,
        "judged": 4,
        "open_defects": 0,
        "severities": [],
        "pins": [],
        "fix_minutes": 0,
    },
    "fairness_report_card": {
        "batch": "BGL-B",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": [],
        "fix_minutes": 0,
    },
    "fairness_test_suite": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": [
            "tests/test_audit_final_release.py",
            "tests/test_audit_wave6_cicd_nan.py",
            "tests/test_junit_xml_escaping.py",
            "tests/test_readiness6_infinity.py",
        ],
        "fix_minutes": 0,
    },
    "fairness_training_analysis": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": [
            "tests/test_audit6_lane3_post_in_processing.py",
            "tests/test_readiness4_constraints.py",
        ],
        "fix_minutes": 0,
    },
    "false_positive_rate_parity_constraint": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 3,
        "open_defects": 0,
        "severities": [],
        "pins": ["tests/test_audit3_inproc_constraints.py"],
        "fix_minutes": 0,
    },
    "false_positive_rate_parity_loss": {
        "batch": "BGL-B",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": [],
        "fix_minutes": 0,
    },
    "feature_attribution_explainer": {
        "batch": "BGL-B",
        "shared_with": [],
        "reached": True,
        "judged": 3,
        "open_defects": 0,
        "severities": [],
        "pins": [],
        "fix_minutes": 0,
    },
    "feature_engineering_analysis": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": ["tests/test_audit_final_release.py"],
        "fix_minutes": 0,
    },
    "feature_suppression": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 4,
        "open_defects": 0,
        "severities": [],
        "pins": ["tests/test_audit6_lane2_feature_engineering.py"],
        "fix_minutes": 0,
    },
    "find_feasible_thresholds": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": ["tests/test_audit_wave1.py"],
        "fix_minutes": 0,
    },
    "find_proxy_chains": {
        "batch": "BGL-B",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": [],
        "fix_minutes": 0,
    },
    "fnr_parity_difference": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": [
            "tests/test_assessability_chain.py",
            "tests/test_audit_wave6_metrics.py",
            "tests/test_readiness4_metrics.py",
        ],
        "fix_minutes": 0,
    },
    "focal_calibrator": {
        "batch": "BGL-B",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": [],
        "fix_minutes": 0,
    },
    "fpr_parity_difference": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": ["tests/test_assessability_chain.py", "tests/test_audit_wave6_metrics.py"],
        "fix_minutes": 0,
    },
    "fpr_parity_difference_with_ci": {
        "batch": "BGL-B",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": [],
        "fix_minutes": 0,
    },
    "generate_annex_iv": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": ["tests/test_compliance_three_state.py"],
        "fix_minutes": 0,
    },
    "generate_dpia_sections": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": ["tests/test_compliance_three_state.py"],
        "fix_minutes": 0,
    },
    "generate_model_card": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": ["tests/test_compliance_three_state.py"],
        "fix_minutes": 0,
    },
    "generate_risk_register": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": ["tests/test_compliance_three_state.py", "tests/test_risk_register_scoring.py"],
        "fix_minutes": 0,
    },
    "group_calibration": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 5,
        "open_defects": 0,
        "severities": [],
        "pins": [
            "tests/test_audit6_lane3_post_in_processing.py",
            "tests/test_readiness2_inert.py",
            "tests/test_readiness6_claims.py",
        ],
        "fix_minutes": 0,
    },
    "group_calibration_metrics": {
        "batch": "BGL-B",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": [],
        "fix_minutes": 0,
    },
    "group_fairness_regularizer": {
        "batch": "BGL-B",
        "shared_with": ["fairness_regularization"],
        "reached": True,
        "judged": 4,
        "open_defects": 0,
        "severities": [],
        "pins": [],
        "fix_minutes": 0,
    },
    "group_threshold": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 3,
        "open_defects": 0,
        "severities": [],
        "pins": [
            "tests/test_audit6_lane3_post_in_processing.py",
            "tests/test_audit6_wave2_argument_order.py",
            "tests/test_audit6_wave4_b_in_processing.py",
            "tests/test_no_aggregator_fabricates_a_verdict.py",
            "tests/test_notebooks_still_run.py",
            "tests/test_readiness2_inert.py",
            "tests/test_site_api_reference_calls_resolve.py",
        ],
        "fix_minutes": 0,
    },
    "groupthink_detector": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": [
            "tests/test_no_aggregator_fabricates_a_verdict.py",
            "tests/test_readiness4_pulse.py",
            "tests/test_readiness6_agents.py",
        ],
        "fix_minutes": 0,
    },
    "hilbert_schmidt_regularizer": {
        "batch": "BGL-B",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": [],
        "fix_minutes": 0,
    },
    "histogram_binning": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 3,
        "open_defects": 0,
        "severities": [],
        "pins": ["tests/test_no_aggregator_fabricates_a_verdict.py"],
        "fix_minutes": 0,
    },
    "identify_privileged_groups": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": [
            "tests/test_audit6_lane4_evaluation.py",
            "tests/test_audit_wave4_evalmetrics.py",
            "tests/test_no_aggregator_fabricates_a_verdict.py",
            "tests/test_readiness_discovery.py",
        ],
        "fix_minutes": 0,
    },
    "identify_proxy_variables": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": ["tests/test_audit6_wave4_f_preprocessing.py", "tests/test_readiness6_names.py"],
        "fix_minutes": 0,
    },
    "in_processing_beta_calibrator": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": ["tests/test_no_aggregator_fabricates_a_verdict.py"],
        "fix_minutes": 0,
    },
    "individual_fairness": {
        "batch": "BGL-B",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": [],
        "fix_minutes": 0,
    },
    "integrated_calibration_index": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": [
            "tests/test_audit_wave6_calibration.py",
            "tests/test_gate_direction.py",
            "tests/test_metric_direction.py",
        ],
        "fix_minutes": 0,
    },
    "integrated_calibration_index_with_ci": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": ["tests/test_audit_wave6_calibration.py"],
        "fix_minutes": 0,
    },
    "integrated_gradients": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": ["tests/test_bgl_final_d01.py", "tests/test_bgl_stage2_s2g09.py"],
        "fix_minutes": 0,
    },
    "interactive_dashboard": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": ["tests/test_readiness5_consumers5.py"],
        "fix_minutes": 0,
    },
    "intersectional_calibration": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": ["tests/test_readiness6_claims.py"],
        "fix_minutes": 0,
    },
    "intersectional_disparity_analysis": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": ["tests/test_audit6_wave3_s03_pulse_ratios.py"],
        "fix_minutes": 0,
    },
    "intersectional_transform": {
        "batch": "BGL-B",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": [],
        "fix_minutes": 0,
    },
    "inverse_propensity": {
        "batch": "BGL-B",
        "shared_with": [],
        "reached": True,
        "judged": 5,
        "open_defects": 0,
        "severities": [],
        "pins": [],
        "fix_minutes": 0,
    },
    "isotonic_calibration": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 3,
        "open_defects": 0,
        "severities": [],
        "pins": ["tests/test_no_aggregator_fabricates_a_verdict.py"],
        "fix_minutes": 0,
    },
    "judge_is_subject": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": ["tests/test_llm_wave0_honesty.py"],
        "fix_minutes": 0,
    },
    "kernel_shap": {
        "batch": "BGL-B",
        "shared_with": [],
        "reached": True,
        "judged": 2,
        "open_defects": 0,
        "severities": [],
        "pins": [],
        "fix_minutes": 0,
    },
    "label_massaging": {
        "batch": "BGL-B",
        "shared_with": [],
        "reached": True,
        "judged": 5,
        "open_defects": 0,
        "severities": [],
        "pins": [],
        "fix_minutes": 0,
    },
    "lime": {
        "batch": "BGL-B",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": [],
        "fix_minutes": 0,
    },
    "linear_explainer": {
        "batch": "BGL-B",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": [],
        "fix_minutes": 0,
    },
    "llm_intersectional_analyzer": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": ["tests/test_llm_wave0_honesty.py"],
        "fix_minutes": 0,
    },
    "lundberg_decomposition": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": ["tests/test_readiness6_claims.py", "tests/xai/test_decomposition.py"],
        "fix_minutes": 0,
    },
    "mae_parity_difference": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": [
            "tests/test_assessability_chain.py",
            "tests/test_perf_scale.py",
            "tests/test_readiness2_headline.py",
            "tests/test_readiness4_docs4.py",
            "tests/test_task_type_detection.py",
        ],
        "fix_minutes": 0,
    },
    "maximum_calibration_error": {
        "batch": "BGL-B",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": [],
        "fix_minutes": 0,
    },
    "mean_prediction_difference": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": [
            "tests/test_assessability_chain.py",
            "tests/test_perf_scale.py",
            "tests/test_pulse_generative_stats.py",
            "tests/test_readiness2_headline.py",
            "tests/test_report_verdict_direction.py",
            "tests/test_task_type_detection.py",
        ],
        "fix_minutes": 0,
    },
    "metrics_store": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": [
            "tests/test_audit6_lane1_reporting.py",
            "tests/test_audit_wave4_ops.py",
            "tests/test_audit_wave5_reportpost.py",
            "tests/test_no_aggregator_fabricates_a_verdict.py",
            "tests/test_readiness5_store5.py",
            "tests/test_readiness6_dashboard.py",
            "tests/test_readiness_reports.py",
        ],
        "fix_minutes": 0,
    },
    "multi_agent_run_harness": {
        "batch": "BGL-B",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": [],
        "fix_minutes": 0,
    },
    "multi_objective_threshold": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 3,
        "open_defects": 0,
        "severities": [],
        "pins": ["tests/test_no_aggregator_fabricates_a_verdict.py"],
        "fix_minutes": 0,
    },
    "multicalibration": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": [
            "tests/test_audit3_ratio_sweep.py",
            "tests/test_audit_wave6_calibration.py",
            "tests/test_audit_wave6_metrics.py",
            "tests/test_gate_direction.py",
            "tests/test_metric_direction.py",
            "tests/test_readiness6_textmatch.py",
            "tests/test_rendering_direction.py",
            "tests/test_report_verdict_direction.py",
            "tests/test_reporting_direction.py",
        ],
        "fix_minutes": 0,
    },
    "multicalibration_with_ci": {
        "batch": "BGL-B",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": [],
        "fix_minutes": 0,
    },
    "multivariate_proxy_leakage": {
        "batch": "BGL-B",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": [],
        "fix_minutes": 0,
    },
    "negative_predictive_value_difference": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": [
            "tests/test_assessability_chain.py",
            "tests/test_readiness4_metrics.py",
            "tests/test_spine_classification_metrics.py",
        ],
        "fix_minutes": 0,
    },
    "negative_predictive_value_difference_with_ci": {
        "batch": "BGL-B",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": [],
        "fix_minutes": 0,
    },
    "negotiation_fairness_tracker": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": [
            "tests/test_no_aggregator_fabricates_a_verdict.py",
            "tests/test_readiness6_agents.py",
        ],
        "fix_minutes": 0,
    },
    "net_benefit_parity": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": ["tests/test_spine_continuous_metrics.py"],
        "fix_minutes": 0,
    },
    "noise_floor_from_runs": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": ["tests/test_llm_wave0_honesty.py", "tests/test_readiness4_nan1.py"],
        "fix_minutes": 0,
    },
    "non_determinism_analyzer": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 2,
        "open_defects": 0,
        "severities": [],
        "pins": ["tests/test_llm_constant_arms_agreement.py", "tests/test_readiness4_nan1.py"],
        "fix_minutes": 0,
    },
    "normalized_discounted_kl_divergence": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": ["tests/test_assessability_chain.py", "tests/test_ranking.py"],
        "fix_minutes": 0,
    },
    "output_analyzer": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 12,
        "open_defects": 0,
        "severities": [],
        "pins": [
            "tests/test_audit_wave5_agentsmisc.py",
            "tests/test_llm.py",
            "tests/test_llm_coverage_survives_correction.py",
            "tests/test_llm_scorer_provenance.py",
            "tests/test_llm_wave0_honesty.py",
            "tests/test_no_aggregator_fabricates_a_verdict.py",
            "tests/test_readiness2_docs2.py",
            "tests/test_readiness2_llmnan.py",
            "tests/test_readiness5_scorer5.py",
        ],
        "fix_minutes": 0,
    },
    "permutation_test": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": [
            "tests/test_bgl_final_audit_repairs.py",
            "tests/test_no_aggregator_fabricates_a_verdict.py",
            "tests/test_no_telemetry.py",
            "tests/test_readiness6_metrics.py",
        ],
        "fix_minutes": 0,
    },
    "pipeline_tracker": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": ["tests/test_audit_wave3.py", "tests/test_readiness6_remainder.py"],
        "fix_minutes": 0,
    },
    "platt_scaling": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 3,
        "open_defects": 0,
        "severities": [],
        "pins": ["tests/test_no_aggregator_fabricates_a_verdict.py"],
        "fix_minutes": 0,
    },
    "platt_scaling_calibrator": {
        "batch": "BGL-B",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": [],
        "fix_minutes": 0,
    },
    "power_analysis": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": [
            "tests/test_audit6_lane4_evaluation.py",
            "tests/test_readiness6_agents.py",
            "tests/test_readiness6_manufactured.py",
        ],
        "fix_minutes": 0,
    },
    "prediction_reweighting": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 4,
        "open_defects": 0,
        "severities": [],
        "pins": [
            "tests/test_audit6_lane3_post_in_processing.py",
            "tests/test_audit6_wave2_argument_order.py",
            "tests/test_audit6_wave2_constraint.py",
            "tests/test_audit_wave2.py",
            "tests/test_notebooks_still_run.py",
        ],
        "fix_minutes": 0,
    },
    "predictive_parity_difference": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": [
            "tests/test_assessability_chain.py",
            "tests/test_audit6_wave4_d_integrations.py",
            "tests/test_audit_wave6_metrics.py",
            "tests/test_explainer_direction.py",
            "tests/test_readiness2_headline.py",
            "tests/test_readiness6_gates.py",
            "tests/test_readiness6_metrics.py",
            "tests/test_rendering_assessable.py",
            "tests/test_task_type_detection.py",
        ],
        "fix_minutes": 0,
    },
    "predictive_parity_difference_with_ci": {
        "batch": "BGL-B",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": [],
        "fix_minutes": 0,
    },
    "pricing_disparity": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": [
            "tests/test_audit_wave6_regression_controls.py",
            "tests/test_spine_continuous_metrics.py",
        ],
        "fix_minutes": 0,
    },
    "pricing_disparity_with_ci": {
        "batch": "BGL-B",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": [],
        "fix_minutes": 0,
    },
    "projected_adversarial": {
        "batch": "BGL-B",
        "shared_with": [],
        "reached": True,
        "judged": 2,
        "open_defects": 0,
        "severities": [],
        "pins": [],
        "fix_minutes": 0,
    },
    "propensity_weighting": {
        "batch": "BGL-B",
        "shared_with": [],
        "reached": True,
        "judged": 5,
        "open_defects": 0,
        "severities": [],
        "pins": [],
        "fix_minutes": 0,
    },
    "proxy_feature_score": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": ["tests/test_readiness6_claims.py", "tests/xai/test_decomposition.py"],
        "fix_minutes": 0,
    },
    "r2_parity_difference": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": ["tests/test_readiness2_headline.py"],
        "fix_minutes": 0,
    },
    "rag_bias_analyzer": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": [
            "tests/test_no_aggregator_fabricates_a_verdict.py",
            "tests/test_readiness4_agents.py",
        ],
        "fix_minutes": 0,
    },
    "recourse_generator": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": ["tests/test_readiness6_metrics.py"],
        "fix_minutes": 0,
    },
    "rejection_option_classification": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 4,
        "open_defects": 0,
        "severities": [],
        "pins": [
            "tests/test_audit6_lane3_post_in_processing.py",
            "tests/test_audit6_wave2_argument_order.py",
            "tests/test_audit6_wave2_constraint.py",
            "tests/test_audit_wave2.py",
            "tests/test_notebooks_still_run.py",
        ],
        "fix_minutes": 0,
    },
    "report_generation": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": [
            "tests/test_no_aggregator_fabricates_a_verdict.py",
            "tests/test_readiness_reports.py",
        ],
        "fix_minutes": 0,
    },
    "representation_bias_amplification": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": [
            "tests/test_audit_wave5_agentsmisc.py",
            "tests/test_vision_homogeneity_is_not_fairness.py",
            "tests/unit/test_vision.py",
        ],
        "fix_minutes": 0,
    },
    "representation_ndkl": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": [
            "tests/test_adapters_ranking_verdicts.py",
            "tests/test_adapters_row_level.py",
            "tests/test_no_aggregator_fabricates_a_verdict.py",
            "tests/test_pulse_generative_stats.py",
            "tests/test_pulse_orchestrator.py",
            "tests/test_ranking.py",
            "tests/test_readiness3_recollapse.py",
            "tests/test_readiness6_detection.py",
            "tests/test_readiness6_manufactured.py",
            "tests/test_vision_homogeneity_is_not_fairness.py",
            "tests/unit/test_vision.py",
        ],
        "fix_minutes": 0,
    },
    "representation_severity": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": [
            "tests/test_audit3_vision_render_tail.py",
            "tests/test_no_aggregator_fabricates_a_verdict.py",
            "tests/test_readiness3_recollapse.py",
            "tests/test_readiness6_manufactured.py",
            "tests/test_vision_homogeneity_is_not_fairness.py",
            "tests/unit/test_vision.py",
        ],
        "fix_minutes": 0,
    },
    "representation_skew": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": [
            "tests/test_audit3_vision_render_tail.py",
            "tests/test_audit_wave5_agentsmisc.py",
            "tests/test_no_aggregator_fabricates_a_verdict.py",
            "tests/test_pulse_deferred_tail.py",
            "tests/test_pulse_pathways.py",
            "tests/test_readiness6_detection.py",
            "tests/test_readiness6_manufactured.py",
            "tests/test_readiness_llmoutage.py",
            "tests/test_risk_register_scoring.py",
            "tests/test_vision_homogeneity_is_not_fairness.py",
            "tests/unit/test_vision.py",
            "tests/xai/test_decomposition.py",
        ],
        "fix_minutes": 0,
    },
    "resampling": {
        "batch": "BGL-B",
        "shared_with": [],
        "reached": True,
        "judged": 4,
        "open_defects": 0,
        "severities": [],
        "pins": [],
        "fix_minutes": 0,
    },
    "residual_bias": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": ["tests/test_readiness2_headline.py"],
        "fix_minutes": 0,
    },
    "residual_transform": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": ["tests/test_audit6_lane2_feature_engineering.py"],
        "fix_minutes": 0,
    },
    "reweighting": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 4,
        "open_defects": 0,
        "severities": [],
        "pins": [
            "tests/test_audit6_lane2_feature_engineering.py",
            "tests/test_audit_wave6_reweighting.py",
        ],
        "fix_minutes": 0,
    },
    "reweighting_analysis": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": ["tests/test_notebooks_still_run.py"],
        "fix_minutes": 0,
    },
    "rmse_parity_difference": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": [
            "tests/test_assessability_chain.py",
            "tests/test_perf_scale.py",
            "tests/test_readiness2_headline.py",
            "tests/test_task_type_detection.py",
        ],
        "fix_minutes": 0,
    },
    "robustness_testing": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": [
            "tests/test_audit_final_release.py",
            "tests/test_readiness6_metrics.py",
            "tests/test_readiness6_textmatch.py",
        ],
        "fix_minutes": 0,
    },
    "sensitivity_analysis": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": ["tests/test_no_aggregator_fabricates_a_verdict.py"],
        "fix_minutes": 0,
    },
    "smote": {
        "batch": "BGL-B",
        "shared_with": [],
        "reached": True,
        "judged": 5,
        "open_defects": 0,
        "severities": [],
        "pins": [],
        "fix_minutes": 0,
    },
    "statistical_parity_regularizer": {
        "batch": "BGL-B",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": [],
        "fix_minutes": 0,
    },
    "stress_test_fairness": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": ["tests/test_no_aggregator_fabricates_a_verdict.py"],
        "fix_minutes": 0,
    },
    "subgroup_robustness_audit": {
        "batch": "BGL-B",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": [],
        "fix_minutes": 0,
    },
    "temperature_scaling": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 3,
        "open_defects": 0,
        "severities": [],
        "pins": [
            "tests/test_audit6_lane3_post_in_processing.py",
            "tests/test_no_aggregator_fabricates_a_verdict.py",
        ],
        "fix_minutes": 0,
    },
    "temperature_scaling_calibrator": {
        "batch": "BGL-B",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": [],
        "fix_minutes": 0,
    },
    "temporal_fairness_analysis": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": ["tests/test_readiness5_store5.py", "tests/test_readiness6_direction.py"],
        "fix_minutes": 0,
    },
    "temporal_tracker": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": [
            "tests/test_agents.py",
            "tests/test_audit6_wave4_a_pulse_assurance.py",
            "tests/test_no_aggregator_fabricates_a_verdict.py",
            "tests/test_readiness6_verdicts.py",
        ],
        "fix_minutes": 0,
    },
    "text_fairness_analyzer": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": [
            "tests/test_no_aggregator_fabricates_a_verdict.py",
            "tests/test_readiness6_agents.py",
        ],
        "fix_minutes": 0,
    },
    "threshold_analysis": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": [
            "tests/test_readiness2_threestate.py",
            "tests/test_readiness6_optimizer.py",
            "tests/test_threshold_analyzer.py",
        ],
        "fix_minutes": 0,
    },
    "threshold_optimization": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 3,
        "open_defects": 0,
        "severities": [],
        "pins": [
            "tests/test_audit6_lane3_post_in_processing.py",
            "tests/test_audit6_wave2_argument_order.py",
            "tests/test_audit6_wave4_b_in_processing.py",
            "tests/test_no_aggregator_fabricates_a_verdict.py",
            "tests/test_notebooks_still_run.py",
            "tests/test_readiness2_inert.py",
            "tests/test_site_api_reference_calls_resolve.py",
        ],
        "fix_minutes": 0,
    },
    "tomek": {
        "batch": "BGL-B",
        "shared_with": [],
        "reached": True,
        "judged": 4,
        "open_defects": 0,
        "severities": [],
        "pins": [],
        "fix_minutes": 0,
    },
    "tool_bias_auditor": {
        "batch": "BGL-B",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": [],
        "fix_minutes": 0,
    },
    "trainable_group_calibrator": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 2,
        "open_defects": 0,
        "severities": [],
        "pins": ["tests/test_readiness2_inert.py"],
        "fix_minutes": 0,
    },
    "tree_shap": {
        "batch": "BGL-B",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": [],
        "fix_minutes": 0,
    },
    "worst_group_accuracy": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": [
            "tests/test_assert_fairness_fail_closed.py",
            "tests/test_audit_wave4_postproc.py",
            "tests/test_no_aggregator_fabricates_a_verdict.py",
            "tests/test_readiness_classification.py",
            "tests/test_rendering_direction.py",
            "tests/test_reporting_direction.py",
        ],
        "fix_minutes": 0,
    },
    "xai_explainer_routing": {
        "batch": "BGL-A",
        "shared_with": [],
        "reached": True,
        "judged": 1,
        "open_defects": 0,
        "severities": [],
        "pins": [
            "tests/test_audit6_wave4_c_xai_router.py",
            "tests/test_audit_wave3.py",
            "tests/xai/test_router.py",
        ],
        "fix_minutes": 0,
    },
}


def proof_status(dispatch_key: str) -> ProofRecord | None:
    """Return the Beta Go-Live proof record for a capability, or None.

    ``None`` means the key is not a registered capability. It does NOT
    mean "clean": an unproven capability has a record whose batch is
    ``BGL-C``. Never collapse the two.
    """
    return CAPABILITY_PROOF.get(dispatch_key)


def proof_summary() -> dict[str, int]:
    """Count of capabilities per batch. The table in the docs is this."""
    out = {b: 0 for b in PROOF_BATCHES}
    for rec in CAPABILITY_PROOF.values():
        out[rec["batch"]] = out.get(rec["batch"], 0) + 1
    return out
