#!/usr/bin/env python3
"""Regenerate ``src/vfairness/_proof_status.py`` from the Beta Go-Live evidence file.

The evidence file (``docs/beta-go-live-census-2026-09-11.json``) is the
record of what was actually EXECUTED against each capability. This script turns
it into the committed ledger, and it FAILS CLOSED at every step:

* a capability with no evidence entry becomes BGL-C UNPROVEN, never BGL-A;
* a BGL-A claim whose pin file does not exist on disk is refused outright;
* a capability present in the registry but absent from the evidence is reported,
  not skipped.

Usage:
    python scripts/beta_go_live_ledger.py            # rewrite the ledger
    python scripts/beta_go_live_ledger.py --check    # exit 1 if it is stale
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
EVIDENCE = ROOT / "docs" / "beta-go-live-census-2026-09-11.json"
LEDGER = ROOT / "src" / "vfairness" / "_proof_status.py"
HEADER = ROOT / "scripts" / "_beta_go_live_header.py"


def assign_batch(rec: dict, pins: list[str]) -> str:
    """The ladder, in one place. Order matters: a defect outranks every pin."""
    if rec.get("open_defects", 0) >= 1:
        return "BGL-D"
    if not rec.get("judged", 0):
        return "BGL-C"
    if not rec.get("reached", False):
        return "BGL-C"
    return "BGL-A" if pins else "BGL-B"


def build() -> tuple[str, dict]:
    from vfairness._registry import CAPABILITY_REGISTRY

    evidence = json.loads(EVIDENCE.read_text(encoding="utf-8"))
    per_cap = evidence["capabilities"]

    records, missing = {}, []
    for key in sorted(CAPABILITY_REGISTRY):
        rec = per_cap.get(key)
        if rec is None:
            missing.append(key)
            rec = {
                "reached": False,
                "judged": 0,
                "open_defects": 0,
                "severities": [],
                "pins": [],
                "fix_minutes": 0,
            }
        # a pin is only a pin if the file is really there
        pins = [p for p in rec.get("pins", []) if (ROOT / p).exists()]
        dropped = set(rec.get("pins", [])) - set(pins)
        if dropped:
            print(
                f"  refusing pin(s) that do not exist for {key}: {sorted(dropped)}", file=sys.stderr
            )
        records[key] = {
            "batch": assign_batch(rec, pins),
            "shared_with": sorted(rec.get("shared_with", [])),
            "reached": bool(rec.get("reached", False)),
            "judged": int(rec.get("judged", 0)),
            "open_defects": int(rec.get("open_defects", 0)),
            "severities": sorted(rec.get("severities", [])),
            "pins": pins,
            "fix_minutes": int(rec.get("fix_minutes", 0)),
        }

    if missing:
        print(
            f"  {len(missing)} registered capabilities have NO evidence entry; "
            f"recorded as BGL-C UNPROVEN: {missing[:5]}{'...' if len(missing) > 5 else ''}",
            file=sys.stderr,
        )

    # The date the COUNTS are true for, which is NOT the census date. The census
    # of MEASURED_ON reproduced far more than what remains; every fix wave since
    # changed the counts and not the census. A consumer given only one date
    # attaches it to whatever number is nearest, which is how a reader concludes
    # the census found 12 when it found 157. Derived from the evidence, never
    # typed: with no stage recorded it falls back to the census date, which is
    # then genuinely the right answer.
    _stage_dates = [
        evidence[k]["date"]
        for k in evidence
        if k.startswith("stage") and isinstance(evidence.get(k), dict) and evidence[k].get("date")
    ]
    counts_as_of = max(_stage_dates) if _stage_dates else evidence["measured_on"]

    body = [
        HEADER.read_text(encoding="utf-8").rstrip(),
        "",
        "",
        f'#: The date the counts below are true for. NOT ``MEASURED_ON``.\nCOUNTS_AS_OF = "{counts_as_of}"',
        "",
        "# Generated by scripts/beta_go_live_ledger.py from",
        "# docs/beta-go-live-census-2026-09-11.json. Do not hand-edit:",
        "# change the evidence and regenerate, so the claim and the record cannot drift.",
        "CAPABILITY_PROOF: dict[str, ProofRecord] = {",
    ]
    for key, r in records.items():
        body.append(f'    "{key}": {{')
        body.append(f'        "batch": "{r["batch"]}",')
        body.append(f'        "shared_with": {r["shared_with"]!r},')
        body.append(f'        "reached": {r["reached"]},')
        body.append(f'        "judged": {r["judged"]},')
        body.append(f'        "open_defects": {r["open_defects"]},')
        body.append(f'        "severities": {r["severities"]!r},')
        body.append(f'        "pins": {r["pins"]!r},')
        body.append(f'        "fix_minutes": {r["fix_minutes"]},')
        body.append("    },")
    body.append("}")
    body.append("")
    body.append("")
    body.append("def proof_status(dispatch_key: str) -> ProofRecord | None:")
    body.append('    """Return the Beta Go-Live proof record for a capability, or None.')
    body.append("")
    body.append("    ``None`` means the key is not a registered capability. It does NOT")
    body.append('    mean "clean": an unproven capability has a record whose batch is')
    body.append("    ``BGL-C``. Never collapse the two.")
    body.append('    """')
    body.append("    return CAPABILITY_PROOF.get(dispatch_key)")
    body.append("")
    body.append("")
    body.append("def proof_summary() -> dict[str, int]:")
    body.append('    """Count of capabilities per batch. The table in the docs is this."""')
    body.append("    out = {b: 0 for b in PROOF_BATCHES}")
    body.append("    for rec in CAPABILITY_PROOF.values():")
    body.append('        out[rec["batch"]] = out.get(rec["batch"], 0) + 1')
    body.append("    return out")
    body.append("")
    text = "\n".join(body)
    # Run the project formatter over the generated text before it is compared or
    # written. Without this, --check diffs the generator's raw repr() against a
    # file ruff has since reformatted, and reports a stale ledger on every run
    # while nothing has actually changed. A gate that cries wolf gets muted.
    return _ruff_format(text), records


def _ruff_format(text: str) -> str:
    """Format generated source with the project's formatter, or return it as-is.

    Falling back rather than failing is deliberate: an environment without ruff
    should still be able to regenerate the ledger. The staleness test runs in an
    environment that HAS ruff, so drift is still caught where it matters.
    """
    import shutil
    import subprocess

    ruff = shutil.which("ruff") or str(ROOT / ".venv" / "bin" / "ruff")
    if not Path(ruff).exists():
        return text
    try:
        proc = subprocess.run(
            [ruff, "format", "-", "--stdin-filename", "_proof_status.py"],
            input=text,
            capture_output=True,
            text=True,
            timeout=60,
        )
    except (OSError, subprocess.SubprocessError):
        return text
    return proc.stdout if proc.returncode == 0 and proc.stdout else text


def _semantically_equal(a: str, b: str) -> bool:
    """True if two sources differ only in formatting."""
    import ast

    try:
        return ast.dump(ast.parse(a)) == ast.dump(ast.parse(b))
    except SyntaxError:
        return False


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--check",
        action="store_true",
        help="exit 1 if the committed ledger differs from the evidence",
    )
    args = ap.parse_args()

    sys.path.insert(0, str(ROOT / "src"))
    text, records = build()

    if args.check:
        current = LEDGER.read_text(encoding="utf-8") if LEDGER.exists() else ""
        # Compare the PARSED form, not the raw text. Comparing text makes the gate
        # depend on whether ruff happened to be on PATH in this environment, so it
        # would pass locally and fail in a CI job with a leaner install while
        # nothing had actually changed. An AST comparison is blind to formatting
        # and catches every change that matters.
        if _semantically_equal(current, text):
            print("ledger is current")
            return 0
        if True:
            print(
                "STALE: _proof_status.py does not match the evidence file.\n"
                "Run: python scripts/beta_go_live_ledger.py",
                file=sys.stderr,
            )
            return 1
        print("ledger is current")
        return 0

    tmp = LEDGER.with_suffix(".py.tmp")
    tmp.write_text(text + "\n", encoding="utf-8")
    tmp.replace(LEDGER)  # atomic: a concurrent reader never sees a partial file

    counts: dict[str, int] = {}
    for r in records.values():
        counts[r["batch"]] = counts.get(r["batch"], 0) + 1
    for b in sorted(counts):
        print(f"  {b}: {counts[b]}")
    print(f"  wrote {LEDGER.relative_to(ROOT)} ({len(records)} capabilities)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
