#!/usr/bin/env python3
"""Render the top of the quality page: is vfairness ready for beta, and what is open.

The page used to open on a long account of the method. A reader asking "can I
rely on this?" had to read thirty sections to find out. This block answers that
first, in the order a reader asks it: the answer, what is guaranteed, what is
only tested, what is open, how it compares with established libraries, and how
it got here. The full method stays below it as the record.

EVERY FIGURE IS READ, NONE IS TYPED:
  docs/gate-checks.json        the two gate checks (scripts/emit_gate_checks.py)
  docs/capability-status.json  the per-unit ledger (scripts/capability_status.py)
  docs/site/data/library-stats.json  tests, coverage, grading (scripts/library_kpis.py)
  docs/readiness-history.json  the dated milestones, a record that must not move

A missing input is stated on the page as missing, never rendered as a pass.

Usage:
    python scripts/render_readiness.py           # write the block into the page
    python scripts/render_readiness.py --check   # exit 1 if the page is stale
"""

from __future__ import annotations

import argparse
import datetime as _dt
import html
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "scripts"))
PAGE = ROOT / "docs" / "site" / "quality-and-hardening" / "index.html"
START, END = "<!-- READINESS:start -->", "<!-- READINESS:end -->"

BROKEN_INPUTS = (
    "only one group",
    "no rows at all",
    "every score missing",
    "one outcome only",
    "every score identical",
    "two rows",
    "a group of one row",
    "a group with no positive outcomes",
)

PLAIN = {
    "B1": "Every code unit examined",
    "B1b": "Each unit's state published where it is documented",
    "B2": "No open defect in code that returns a fairness number",
    "B2b": "Every finding of the second audit closed",
    "B3": "Every open defect ranked by severity",
    "B4": "Every grade confirmed by a second, independent examiner",
    "B5": "All 215 capabilities examined, none open",
    "B6": "Same answer as established libraries",
    "B7": "No invented numbers on broken data",
}

HEAT_HELP = (
    (
        "Code units examined",
        "Every function, class and method was run on normal and broken data and the result "
        "written down. Amber or red: some code here has never been run, so it could give a "
        "wrong answer and nobody would know.",
    ),
    (
        "Re-checked by a second examiner",
        "A second, independent reviewer tries to prove the first grade wrong. Amber or red "
        "means NOT YET re-checked, not failed. Where a re-check did happen, about one in "
        "three first grades was overturned, so a grade not yet re-checked is evidence, not proof.",
    ),
    (
        "Open defects",
        "Problems proved by running the code and not fixed yet. Red: there is a known way "
        "this area gives a wrong answer today.",
    ),
    (
        "Same answer as an established library",
        "Computed by vfairness and by fairlearn, scikit-learn, statsmodels or scipy on the "
        "same clean data. Red: the numbers differ. Grey: no other library computes it, so "
        "only vfairness's own tests vouch for it.",
    ),
    (
        "No invented numbers on broken data",
        "Fed data where its number cannot exist, it must refuse. Red: it can report "
        'something like 0.0, "no bias", when nothing was measured.',
    ),
)

AREA_OF = {
    # Plain-language family for the capabilities with no outside reference.
    "Explainer": "explainers",
    "Analyzer": "LLM and agent analysis",
    "Detector": "LLM and agent analysis",
    "Tester": "LLM and agent analysis",
    "Runner": "LLM benchmarks",
    "Tracker": "agent and multi-agent tracking",
    "Auditor": "agent and multi-agent tracking",
    "Graph": "causal analysis",
}


def _read(path: Path):
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception:  # noqa: BLE001 - reported on the page
        return None


def _date(iso: str) -> str:
    try:
        d = _dt.date.fromisoformat(iso)
        return f"{d.day} {d.strftime('%b %Y')}"
    except Exception:  # noqa: BLE001
        return html.escape(iso or "unknown date")


def _pretty(name: str) -> str:
    return name.replace("_", " ")


CSS = """<style>
/* Readiness block: generated by scripts/render_readiness.py */
.rd { --rd-ok: #0f9f6e; --rd-ok-bg: #e7f7f0; --rd-mid: #2563eb; --rd-mid-bg: #eaf1fe;
  --rd-open: #b45309; --rd-open-bg: #fdf3e3; --rd-ink: var(--color-gray-900, #111827);
  --rd-soft: var(--color-gray-600, #4b5563); --rd-line: var(--color-gray-200, #e5e7eb);
  --rd-card: var(--color-white, #ffffff); --rd-ground: var(--color-gray-50, #f9fafb);
  color: var(--rd-ink); }
/* No dark override: the site renders light in every scheme, and a dark block on a
   light page was unreadable (seen 2026-10-01 in a dark-scheme browser). */
.rd h1 { margin-bottom: .25rem; }
.rd-eyebrow { font-size: .72rem; font-weight: 700; letter-spacing: .09em; text-transform: uppercase;
  color: var(--rd-soft); }
.rd-answer { display: grid; grid-template-columns: auto 1fr; gap: 1.25rem; align-items: center;
  border: 1px solid var(--rd-line); border-left: 6px solid var(--rd-state); border-radius: 14px;
  background: var(--rd-card); padding: 1.4rem 1.6rem; margin: 1.25rem 0 1.5rem; }
.rd-answer__badge { font-weight: 800; font-size: 1.05rem; color: var(--rd-state);
  background: var(--rd-state-bg); border-radius: 999px; padding: .55rem 1.1rem; white-space: nowrap; }
.rd-answer p { margin: 0; font-size: 1.05rem; line-height: 1.55; }
.rd-tiles { display: grid; grid-template-columns: repeat(auto-fit, minmax(190px, 1fr)); gap: .9rem;
  margin: 0 0 2.5rem; }
.rd-tile { border: 1px solid var(--rd-line); border-radius: 12px; background: var(--rd-card);
  padding: 1rem 1.1rem; display: flex; flex-direction: column; gap: .35rem; }
.rd-tile__big { font-size: 1.9rem; font-weight: 800; line-height: 1.05; font-variant-numeric: tabular-nums; }
.rd-tile__big small { font-size: 1rem; font-weight: 600; color: var(--rd-soft); }
.rd-tile__label { font-size: .9rem; color: var(--rd-soft); line-height: 1.4; }
.rd-bar { height: 6px; border-radius: 6px; background: var(--rd-line); overflow: hidden; margin-top: .3rem; }
.rd-bar span { display: block; height: 100%; background: var(--rd-ok); }
.rd h2 { margin-top: 2.5rem; }
.rd-cols { display: grid; grid-template-columns: repeat(auto-fit, minmax(250px, 1fr)); gap: 1rem; }
.rd-col { border-radius: 14px; padding: 1.2rem 1.25rem; background: var(--rd-col-bg);
  border: 1px solid var(--rd-line); }
.rd-col h3 { margin: 0 0 .2rem; font-size: 1.05rem; color: var(--rd-col); }
.rd-col .rd-sub { margin: 0 0 .8rem; font-size: .85rem; color: var(--rd-soft); }
.rd-col ul { margin: 0; padding-left: 1.1rem; display: grid; gap: .6rem; }
.rd-col li { line-height: 1.5; font-size: .95rem; }
.rd-col--ok { --rd-col: var(--rd-ok); --rd-col-bg: var(--rd-ok-bg); }
.rd-col--mid { --rd-col: var(--rd-mid); --rd-col-bg: var(--rd-mid-bg); }
.rd-col--open { --rd-col: var(--rd-open); --rd-col-bg: var(--rd-open-bg); }
.rd .rd-col ul.rd-chips { display: flex; flex-wrap: wrap; gap: .35rem; margin: .6rem 0 0; padding: 0;
  list-style: none; }
.rd .rd-col ul.rd-chips li { font-size: .76rem; line-height: 1.3; border: 1px solid var(--rd-line);
  background: var(--rd-card); border-radius: 999px; padding: .2rem .6rem; }
.rd .rd-col ul.rd-chips li::before { content: none; }
.rd-libs { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: .9rem; margin: 1rem 0 .5rem; }
.rd-lib { border: 1px solid var(--rd-line); border-radius: 12px; background: var(--rd-card); padding: 1rem 1.1rem; }
.rd-lib__name { font-weight: 800; font-size: 1.05rem; }
.rd-lib__count { font-size: .9rem; color: var(--rd-soft); margin: .15rem 0 .5rem; }
.rd-lib__ok { color: var(--rd-ok); font-weight: 700; font-size: .9rem; }
.rd-lib__bad { color: var(--rd-open); font-weight: 700; font-size: .9rem; }
.rd-table { width: 100%; border-collapse: collapse; font-size: .92rem; }
.rd-table th, .rd-table td { text-align: left; padding: .5rem .6rem; border-bottom: 1px solid var(--rd-line); }
.rd-table th { font-size: .75rem; text-transform: uppercase; letter-spacing: .06em; color: var(--rd-soft); }
.rd-table td.rd-yes { color: var(--rd-ok); font-weight: 700; white-space: nowrap; }
.rd-table td.rd-no { color: var(--rd-open); font-weight: 700; white-space: nowrap; }
.rd-scroll { overflow-x: auto; border: 1px solid var(--rd-line); border-radius: 12px; background: var(--rd-card); }
.rd-note { color: var(--rd-soft); font-size: .9rem; line-height: 1.55; }
.rd-steps { display: grid; grid-template-columns: repeat(auto-fit, minmax(260px, 1fr)); gap: 1rem; }
.rd-step { border: 1px solid var(--rd-line); border-radius: 12px; padding: 1rem 1.2rem; background: var(--rd-card); }
.rd-step h3 { margin: 0 0 .4rem; font-size: 1rem; }
.rd-step p { margin: 0; font-size: .93rem; line-height: 1.55; }
.rd ul.rd-time { list-style: none; margin: 1rem 0 0 .4rem; padding: 0 0 0 1.4rem; border-left: 2px solid var(--rd-line); }
.rd ul.rd-time > li { position: relative; padding: 0 0 1.4rem .6rem; list-style: none; }
.rd ul.rd-time > li::before { content: ""; position: absolute; left: -1.95rem; top: .3rem; width: 12px; height: 12px;
  border-radius: 50%; background: var(--rd-card); border: 3px solid var(--rd-mid); }
.rd ul.rd-time > li:last-child::before { border-color: var(--rd-ok); background: var(--rd-ok); }
.rd-time time { font-size: .78rem; font-weight: 700; letter-spacing: .05em; text-transform: uppercase; color: var(--rd-soft); }
.rd-time h3 { margin: .1rem 0 .25rem; font-size: 1.02rem; }
.rd-time p { margin: 0; font-size: .94rem; line-height: 1.55; max-width: 70ch; }
details.rd-more { margin-top: .8rem; }
.rd-conds { width: 100%; border-collapse: collapse; font-size: .92rem; margin: -.5rem 0 2rem; }
.rd-conds td { padding: .45rem .6rem; border-bottom: 1px solid var(--rd-line); vertical-align: top; }
.rd-conds td:first-child { width: 6.5rem; }
.rd-conds td.rd-fig { width: 11rem; font-weight: 800; font-size: 1rem; white-space: nowrap;
  font-variant-numeric: tabular-nums; }
.rd-fig--ok { color: var(--rd-ok); } .rd-fig--open { color: var(--rd-open); }
/* "?" explainers: a real element, shown on hover, keyboard focus and tap. The
   browser's title tooltip was slow, easy to miss and absent on phones. */
.rd-q { position: relative; display: inline-flex; align-items: center; justify-content: center;
  width: 1.15rem; height: 1.15rem; border-radius: 50% !important; border: 1.5px solid var(--rd-mid);
  background: var(--rd-card); color: var(--rd-mid); font: 800 .72rem/1 var(--font-sans, sans-serif);
  cursor: help; padding: 0; margin-left: .35rem; vertical-align: 2px; }
.rd-q:hover, .rd-q:focus { background: var(--rd-mid); color: #fff; outline: none; }
.rd-q__pop { display: none; position: absolute; z-index: 50; top: calc(100% + 8px); left: 50%;
  transform: translateX(-50%); width: 300px; max-width: 80vw; text-align: left; white-space: normal;
  background: var(--rd-ink); color: #fff; font: 400 .85rem/1.5 var(--font-sans, sans-serif);
  letter-spacing: 0; text-transform: none; border-radius: 10px; padding: .75rem .9rem;
  box-shadow: 0 10px 30px rgba(0, 0, 0, .25); }
.rd-q__pop strong { color: #fff; }
.rd-q:hover .rd-q__pop, .rd-q:focus .rd-q__pop, .rd-q:focus-within .rd-q__pop { display: block; }
.rd-q--left .rd-q__pop { left: auto; right: -8px; transform: none; }
.rd-line { border: 1px solid var(--rd-line); border-radius: 12px; padding: 1rem 1.2rem;
  background: var(--rd-ground); margin: 0 0 1rem; }
.rd-line h3 { margin: 0 0 .35rem; font-size: 1rem; }
.rd-line p { margin: 0; line-height: 1.55; font-size: .95rem; }
.rd ul.rd-logic { margin: .4rem 0 0; padding-left: 1.1rem; display: grid; gap: .45rem; font-size: .93rem; line-height: 1.5; }
.rd-line--later { margin-top: .5rem; }
.rd-line--later .rd-conds { margin: .6rem 0 0; }
.rd-conds .rd-m { color: var(--rd-soft); font-size: .85rem; }
.rd-pill { display: inline-block; font-size: .72rem; font-weight: 800; letter-spacing: .05em;
  text-transform: uppercase; border-radius: 999px; padding: .15rem .55rem; }
.rd-pill--ok { color: var(--rd-ok); background: var(--rd-ok-bg); }
.rd-pill--open { color: var(--rd-open); background: var(--rd-open-bg); }
.rd-heat { width: 100%; min-width: 760px; table-layout: fixed; border-collapse: separate;
  border-spacing: 3px; font-size: .86rem; }
.rd-heat col.rd-c-area { width: 20%; } .rd-heat col.rd-c { width: 16%; }
/* Even rows: one height for every row, two lines of text or one. */
.rd-heat tbody td { height: 3.1rem; vertical-align: middle; line-height: 1.25; overflow: hidden; }
.rd-heat thead th { height: 4.6rem; }
.rd-heat th { font-size: .72rem; text-transform: uppercase; letter-spacing: .05em; color: var(--rd-soft);
  text-align: center; padding: .4rem .3rem; vertical-align: bottom; }
.rd-heat th:first-child, .rd-heat td:first-child { text-align: left; }
.rd-heat td { padding: .45rem .5rem; text-align: center; border-radius: 6px; white-space: nowrap;
  font-variant-numeric: tabular-nums; }
.rd-heat td:first-child { white-space: normal; font-weight: 600; }
.rd-h-g { background: #c9efdc; color: #075e3f; }
.rd-h-a { background: #fde9bf; color: #7a4a02; }
.rd-h-r { background: #fbd0cc; color: #8a1c12; }
.rd-h-n { background: var(--rd-ground); color: var(--rd-soft); }
.rd-stamp { display: inline-block; font-size: .88rem; background: var(--rd-ground);
  border: 1px solid var(--rd-line); border-radius: 8px; padding: .45rem .8rem; margin: 0 0 .8rem; }
.rd-guide td { vertical-align: top; font-size: .86rem; line-height: 1.45; min-width: 150px; }
.rd-guide td:first-child { min-width: 130px; }
.rd-legend { display: flex; flex-wrap: wrap; gap: .8rem; font-size: .82rem; color: var(--rd-soft); margin: .6rem 0 0; }
.rd-legend span::before { content: ""; display: inline-block; width: .8rem; height: .8rem; border-radius: 3px;
  margin-right: .35rem; vertical-align: -1px; }
.rd-legend .g::before { background: #c9efdc; } .rd-legend .a::before { background: #fde9bf; }
.rd-legend .r::before { background: #fbd0cc; } .rd-legend .n::before { background: var(--rd-line); }
details.rd-more summary { cursor: pointer; color: var(--rd-mid); font-weight: 600; }
@media (max-width: 640px) { .rd-answer { grid-template-columns: 1fr; padding: 1rem; }
  .rd-answer__badge { white-space: normal; } .rd-conds td.rd-fig { width: auto; white-space: normal; } }
</style>"""


def _measured(c: dict, unconfirmed: int, examined: int) -> str:
    """A condition's measurement in the reader's units: code units, as in the heat map."""
    if c["id"] == "B4" and not c["passes"]:
        return (
            f"{unconfirmed:,} of {examined:,} examined code units still need a second examiner "
            f"(the gate counts {c['measured']} grades; some are a second name for the same code)"
        )
    if c["id"] == "B1" and not c["passes"]:
        import re

        names = re.findall(r"vfairness\.[\w.]+", str(c["measured"]))
        short = ", ".join(n.rsplit(".", 2)[-2] + "." + n.rsplit(".", 1)[-1] for n in names)
        return f"{len(names)} small helper functions have never been run by any test: {short}"
    if c["id"] == "B3":
        return (
            "every known defect carries a severity"
            if c["passes"]
            else f"some open defects have no severity yet ({c['measured']})"
        )
    if c["id"] == "B5":
        return "every registered capability graded; none open, none unproven"
    return str(c["measured"])


def _q(text: str, left: bool = False) -> str:
    """A "?" marker whose explanation shows on hover, focus or tap."""
    cls = "rd-q rd-q--left" if left else "rd-q"
    return (
        f'<button type="button" class="{cls}" aria-label="What this means">?'
        f'<span class="rd-q__pop" role="tooltip">{html.escape(text)}</span></button>'
    )


def _cell(
    num: int,
    den: int,
    green_at: float = 1.0,
    amber_at: float = 0.5,
    na: str = "n/a",
    gap: str = "",
    na_tip: str = "",
) -> str:
    """One heat-map cell. ``gap`` names the missing part, e.g. "{n} grades never re-checked"."""
    if den == 0:
        return f'<td class="rd-h-n" title="{html.escape(na_tip)}">{na}</td>'
    share = num / den
    cls = "rd-h-g" if share >= green_at else ("rd-h-a" if share >= amber_at else "rd-h-r")
    tip = "All done." if num == den else gap.format(n=den - num)
    return f'<td class="{cls}" title="{html.escape(tip)}">{num:,} / {den:,}</td>'


def _heatmap(led: dict, unaudited: set, c1: dict, c2: dict, S) -> str:
    """One row per area, one column per condition, coloured by how far it is done."""
    from vfairness._registry import CAPABILITY_REGISTRY

    units = led["units"]
    area_of_cap = {}
    for e in CAPABILITY_REGISTRY.values():
        if e["pipeline_stage"] != "evaluation":
            continue
        name, mod = e["name"], "vfairness." + e["module_path"]
        hits = [q for q in units if q.endswith("." + name)]
        best = [q for q in hits if q.startswith(mod)] or hits
        area_of_cap[name] = units[best[0]]["area"] if best else "Top level"
    ref = {r["name"]: r["agree"] for r in c1.get("rows", [])}
    verdicts = c2.get("verdicts", {})

    rows = []
    for area in sorted(
        {r["area"] for r in units.values()},
        # Ties broken by name: two areas of equal size otherwise fall back to set
        # order, which Python randomises per process, and the --check in
        # refresh-docs.sh failed on alternate runs (seen four times 2026-10-01).
        key=lambda a: (-sum(1 for r in units.values() if r["area"] == a), a),
    ):
        au = {q: r for q, r in units.items() if r["area"] == area}
        total = len(au)
        examined = sum(1 for r in au.values() if r["status"] == S.CHECKED)
        confirmed = sum(1 for q, r in au.items() if r["status"] == S.CHECKED and q not in unaudited)
        fixes = sum(1 for r in au.values() if r["status"] == S.FIX_PENDING)
        caps = [n for n, a in area_of_cap.items() if a == area]
        with_ref = [n for n in caps if n in ref]
        measuring = [n for n in caps if verdicts.get(n) not in (None, "NOT A MEASUREMENT")]
        honest = [n for n in measuring if verdicts.get(n) == "PASS"]
        defect_cell = (
            '<td class="rd-h-g" title="No known defect in this area.">0</td>'
            if fixes == 0
            else f'<td class="rd-h-r" title="{fixes} proven defect(s) not yet fixed here.">{fixes}</td>'
        )
        rows.append(
            f"<tr><td>{html.escape(area)}</td>"
            + _cell(
                examined,
                total,
                green_at=1.0,
                amber_at=0.95,
                gap="{n} code unit(s) here have never been run by any test.",
            )
            + _cell(
                confirmed,
                examined,
                green_at=1.0,
                amber_at=0.5,
                gap="{n} grade(s) here have not been re-checked by a second examiner yet. Not failed: not yet looked at.",
            )
            + defect_cell
            + _cell(
                sum(1 for n in with_ref if ref[n]),
                len(with_ref),
                na="no reference",
                gap="{n} capability(ies) here give a different number from the reference library.",
                na_tip="No established library computes these numbers, so there is nothing to compare with.",
            )
            + _cell(
                len(honest),
                len(measuring),
                na="no measuring capability",
                gap="{n} capability(ies) here can invent a number on broken data.",
                na_tip="Nothing in this area produces a fairness number, so this check does not apply.",
            )
            + "</tr>"
        )
    head = (
        "<thead><tr><th>Area</th>"
        + "".join(
            f"<th>{title}{_q(text, left=i >= 3)}</th>" for i, (title, text) in enumerate(HEAT_HELP)
        )
        + "</tr></thead>"
    )
    cols = '<colgroup><col class="rd-c-area">' + '<col class="rd-c">' * 5 + "</colgroup>"
    return f'<table class="rd-heat">{cols}{head}<tbody>{"".join(rows)}</tbody></table>'


def render() -> str:
    gate = _read(ROOT / "docs" / "gate-checks.json")
    stats = _read(ROOT / "docs" / "site" / "data" / "library-stats.json") or {}
    hist = _read(ROOT / "docs" / "readiness-history.json") or {"milestones": []}
    import stamp_status_badges as S

    led = S.load()
    units = led["units"]
    n_unchecked = sum(1 for r in units.values() if r["status"] == S.NOT_CHECKED)
    n_fix = sum(1 for r in units.values() if r["status"] == S.FIX_PENDING)
    unaudited, overturned, audited_ever = S._independent_check()
    k = stats.get("kpis", {}).get("hardening", {})
    tests = k.get("tests", {}).get("collected")
    cov = k.get("ci", {}).get("coverage_pct")
    defects_open = k.get("defects", {}).get("open")
    version = html.escape(str(stats.get("version", "")))

    if not gate:
        return (
            f'{START}\n{CSS}\n<section class="rd" id="readiness"><h1>Quality &amp; Hardening</h1>'
            "<p><strong>The beta gate has not been run for this build</strong>, so this page does "
            f"not say whether vfairness is ready.</p></section>\n{END}"
        )
    c1 = gate["check1_correct_on_normal_data"]
    c2 = gate["check2_honest_on_broken_data"]
    # ONE GATE. The badge is the formal beta gate in scripts/release_gate.py, of
    # which the two executable checks are conditions B6 and B7. On 2026-10-01 this
    # page said "Beta gate passed" from the two checks alone while that gate said
    # NOT BETA READY; two gates with two answers is the confusion this block exists
    # to remove.
    import release_gate as RG

    beta = RG._beta_criteria()
    full = RG._criteria()
    later = [c for c in full if c["id"] in ("G1", "G2")]
    passes = all(c["passes"] for c in beta)
    n_ok = sum(1 for c in beta if c["passes"])
    state = (
        ("var(--rd-ok)", "var(--rd-ok-bg)") if passes else ("var(--rd-open)", "var(--rd-open-bg)")
    )
    badge = (
        "Beta-ready"
        if passes
        else f"Not beta-ready yet: {len(beta) - n_ok} of {len(beta)} conditions open"
    )
    nam = c2.get("not_a_measurement", 0)
    honest = c2["pass"]
    # The registry's evaluation stage holds entries that were run and shown to produce
    # no number at all; they cannot invent one, so they are named, not counted as passes.
    entries = c2["entries"] - nam
    if passes:
        answer = (
            f"All {len(beta)} beta conditions are met. Every one of the {entries} capabilities that produce a fairness number has passed "
            f"both checks below. Where an established library computes the same number, "
            f"vfairness gives the same answer. Where the data cannot support a number, it says "
            f"so instead of inventing one. What is still open is listed below, plainly."
        )
    else:
        failing = [c for c in beta if not c["passes"]]
        b67 = all(c["passes"] for c in beta if c["id"] in ("B6", "B7"))
        answer = (
            (
                "The numbers themselves pass: where an established library computes the same "
                "number, vfairness agrees, and nothing invents a number on broken data. "
                if b67
                else ""
            )
            + f"{n_ok} of {len(beta)} beta conditions are met. Still open: "
            + "; ".join(PLAIN.get(c["id"], c["name"]).lower() for c in failing)
            + "."
        )

    c1_ok = c1.get("state") == "ran"
    tiles = [
        (
            f"{c1['agree']}<small> / {c1['with_reference']}</small>" if c1_ok else "not run",
            "give the same number as an established library (fairlearn, scikit-learn, statsmodels, scipy)",
            (c1["agree"] / c1["with_reference"]) if c1_ok and c1["with_reference"] else 0,
        ),
        (
            f"{honest}<small> / {entries}</small>",
            "capabilities that measure refuse to invent a number when the data cannot support one",
            honest / entries if entries else 0,
        ),
        (
            f"{defects_open if defects_open is not None else '?'}",
            "known defects open. Every defect proved by running the code is fixed",
            1.0 if defects_open == 0 else 0,
        ),
        (
            f"{tests:,}" if isinstance(tests, int) else "?",
            f"automated tests, reaching {cov}% of lines and branches" if cov else "automated tests",
            (cov or 0) / 100,
        ),
    ]
    n_exam_u = sum(1 for r in units.values() if r["status"] == S.CHECKED)
    n_unconf_u = sum(1 for q, r in units.items() if r["status"] == S.CHECKED and q in unaudited)
    import re as _re

    def _ints(text: str) -> list[int]:
        return [int(x.replace(",", "")) for x in _re.findall(r"\d[\d,]*", str(text))]

    never_run = sum(
        1 for r in units.values() if r["status"] == S.NOT_CHECKED and not r.get("grade")
    )
    n_caps = stats.get("capabilities") or 215

    def _figure(c: dict) -> str:
        """The condition's number, in the unit a reader counts."""
        i, m = c["id"], c["measured"]
        if i == "B1":
            return f"{len(units) - never_run:,} / {len(units):,} run"
        if i == "B1b":
            n = _ints(m)
            return f"{n[0]:,} / {n[1]:,} published" if len(n) >= 2 else "?"
        if i in ("B2", "B3"):
            n = _ints(m)
            return f"{n[0]:,} open" if n else "?"
        if i == "B2b":
            n = _ints(m)
            return f"{n[0]:,} of {n[1]:,} open" if len(n) >= 2 else "?"
        if i == "B4":
            return f"{n_exam_u - n_unconf_u:,} / {n_exam_u:,} confirmed"
        if i == "B5":
            return f"{n_caps} / {n_caps} clear" if c["passes"] else "open"
        if i == "B6" and c1_ok:
            return f"{c1['agree']} / {c1['with_reference']} match"
        if i == "B7":
            return f"{c2['pass']} / {c2['entries'] - c2.get('not_a_measurement', 0)} honest"
        return ""

    def _tip(c: dict) -> str:
        return f"{RG.PLAIN_ENGLISH.get(c['id'], '')} Why it matters: {c.get('why', '')}".strip()

    later_rows = "".join(
        "<tr>"
        f'<td><span class="rd-pill rd-pill--{"ok" if c["passes"] else "open"}">'
        f"{'Met' if c['passes'] else 'Open'}</span></td>"
        f'<td class="rd-fig rd-fig--{"ok" if c["passes"] else "open"}">'
        + html.escape(
            f"{n_exam_u - n_unconf_u:,} / {n_exam_u:,} confirmed"
            if c["id"] == "G2"
            else str(c["measured"])
        )
        + "</td>"
        f"<td><strong>{html.escape('Every grade confirmed by a second, independent examiner' if c['id'] == 'G2' else 'Every code unit carries a grade')}</strong>"
        + _q(str(c.get("why", "")))
        + "</td></tr>"
        for c in later
    )
    conds = "".join(
        "<tr>"
        f'<td><span class="rd-pill rd-pill--{"ok" if c["passes"] else "open"}">'
        f"{'Met' if c['passes'] else 'Open'}</span></td>"
        f'<td class="rd-fig rd-fig--{"ok" if c["passes"] else "open"}">{html.escape(_figure(c))}</td>'
        f"<td><strong>{html.escape(PLAIN.get(c['id'], c['name']))}</strong>"
        + _q(_tip(c))
        + f'<div class="rd-m">{html.escape(_measured(c, n_unconf_u, n_exam_u))[:240]}</div></td></tr>'
        for c in beta
    )
    tiles_html = "\n".join(
        f'<div class="rd-tile"><span class="rd-tile__big">{big}</span>'
        f'<span class="rd-tile__label">{label}</span>'
        f'<div class="rd-bar"><span style="width:{max(0.0, min(1.0, share)) * 100:.0f}%"></span></div></div>'
        for big, label, share in tiles
    )

    chips = "".join(f"<li>{html.escape(x)}</li>" for x in BROKEN_INPUTS)
    no_ref = c1.get("no_reference_names", [])
    families = sorted({v for n in no_ref for suf, v in AREA_OF.items() if n.endswith(suf)})
    ok_items = [
        f"<strong>Same answer as the reference libraries.</strong> {c1['agree']} metrics are "
        "computed side by side with an established library on clean data, two groups and three "
        "groups of unequal size, and must match to the ninth decimal."
        if c1_ok
        else "<strong>Reference comparison could not run</strong> for this build.",
        f"<strong>No invented numbers.</strong> All {entries} measuring capabilities are fed eight "
        "kinds of broken data. Each must refuse, or say it could not measure, and must still "
        'measure the healthy data alongside.<ul class="rd-chips">' + chips + "</ul>",
        "<strong>Three answers, never two.</strong> A result is measured, failed, or "
        "could-not-check, and the third is written into the result itself, not only into a "
        "warning that most programs never show.",
    ]
    if nam:
        ok_items[1] += (
            f" {nam} more {'is' if nam == 1 else 'are'} registered beside them but "
            f"{'produces' if nam == 1 else 'produce'} no number at all (run and confirmed), "
            "so there is nothing to invent."
        )
    mid_items = [
        f"<strong>{c1['no_reference']} capabilities have no outside reference</strong>"
        + (f" ({', '.join(families)} and others)" if families else "")
        + ". No other library computes these numbers, so their accuracy on normal data rests on "
        "vfairness's own tests. They are still checked never to invent a number.",
        f"<strong>{tests:,} automated tests</strong> run on every change, reaching {cov}% of "
        "lines and branches. Covered code can still be wrong; this says it was exercised."
        if isinstance(tests, int) and cov
        else "<strong>Automated tests</strong> run on every change.",
    ]
    open_items = []
    # Counted in CODE UNITS, the heat map's denominator. The gate's B4 counts grades
    # (612 on 2026-10-01), ten of which are a second import name for the same code.
    examined_units = [q for q, r in units.items() if r["status"] == S.CHECKED]
    n_unconfirmed = sum(1 for q in examined_units if q in unaudited)
    if n_unconfirmed:
        rate = (
            f", and {overturned:,} of the {audited_ever:,} re-checked so far were overturned"
            if overturned and audited_ever
            else ""
        )
        open_items.append(
            f"<strong>{n_unconfirmed:,} of {len(examined_units):,} examined code units have not "
            f"had a second, independent check</strong>{rate}. Treat those grades as evidence, "
            "not proof."
        )
    never = sum(1 for r in units.values() if r["status"] == S.NOT_CHECKED and not r.get("grade"))
    unreached = n_unchecked - never
    if never:
        open_items.append(
            f"<strong>{never} code units</strong> have never been run by any test yet."
        )
    if unreached:
        open_items.append(
            f"<strong>{unreached} code {'unit was' if unreached == 1 else 'units were'} examined but "
            "could not be reached</strong> by any test input, so nothing is known about "
            f"{'it' if unreached == 1 else 'them'}."
        )
    if n_fix:
        open_items.append(f"<strong>{n_fix} code units</strong> have a known fix pending.")
    open_items += [
        f"<strong>Not yet published.</strong> Version {version} has never been released to PyPI; "
        "the release pipeline is built and gated but has not run.",
        "<strong>Some checks have not produced a result yet</strong>: code scanning (CodeQL, "
        "OpenSSF Scorecard) waits for the public repository, and mutation testing covers one "
        "module.",
    ]

    heat = _heatmap(led, unaudited, c1, c2, S)
    recheck_sentence = (
        f"of the {audited_ever:,} grades re-checked so far, {overturned:,} were overturned, "
        f"about one in {round(audited_ever / overturned)}. The first examiner had sometimes "
        "missed a real defect. Every defect a re-check uncovered was fixed: none is open today."
        if overturned and audited_ever
        else "the overturn rate of re-checked grades could not be read for this build."
    )
    # The figures are as of the newest of their sources, never the day the page was
    # built: a build date would claim a freshness the evidence does not have.
    asof = max(d for d in (gate.get("date", ""), led.get("newest_evidence", "")) if d)

    def col(cls, title, sub, items):
        lis = "".join(f"<li>{x}</li>" for x in items)
        return f'<div class="rd-col rd-col--{cls}"><h3>{title}</h3><p class="rd-sub">{sub}</p><ul>{lis}</ul></div>'

    cols = "\n".join(
        [
            col("ok", "Guaranteed", "A test fails the moment this stops being true.", ok_items),
            col(
                "mid",
                "Tested",
                "Checked by vfairness's own tests, not against an outside reference.",
                mid_items,
            ),
            col("open", "Open", "Not done yet, or not proven yet.", open_items),
        ]
    )

    rows = "".join(
        f"<tr><td>{html.escape(_pretty(r['name']))}</td><td>{html.escape(r['reference'])}</td>"
        + ('<td class="rd-yes">Matches</td>' if r["agree"] else '<td class="rd-no">Differs</td>')
        + "</tr>"
        for r in c1.get("rows", [])
    )
    fams = {}
    for r in c1.get("rows", []):
        ref = r["reference"].lower()
        fam = (
            "fairlearn"
            if "fairlearn" in ref
            else "statsmodels"
            if "statsmodels" in ref
            else "scipy"
            if "scipy" in ref
            else "scikit-learn"
        )
        f = fams.setdefault(fam, [0, 0])
        f[0] += 1
        f[1] += 1 if r["agree"] else 0
    libs = "".join(
        f'<div class="rd-lib"><div class="rd-lib__name">{fam}</div>'
        f'<div class="rd-lib__count">{n} {"capability" if n == 1 else "capabilities"} compared</div>'
        + (
            f'<span class="rd-lib__ok">All {n} match</span>'
            if ok == n
            else f'<span class="rd-lib__bad">{n - ok} differ</span>'
        )
        + "</div>"
        for fam, (n, ok) in sorted(fams.items(), key=lambda kv: -kv[1][0])
    )
    noref_list = ", ".join(html.escape(_pretty(n)) for n in no_ref)

    timeline = "".join(
        f'<li><time datetime="{html.escape(m["date"])}">{_date(m["date"])}</time>'
        f"<h3>{html.escape(m['title'])}</h3><p>{html.escape(m['text'])}</p></li>"
        for m in hist.get("milestones", [])
    )

    return f"""{START}
{CSS}
<section class="rd" id="readiness">
  <span class="rd-eyebrow">vfairness {version} &middot; beta readiness &middot; checked {_date(gate.get("date", ""))}</span>
  <h1>Quality &amp; Hardening</h1>
  <div class="rd-answer" style="--rd-state:{state[0]};--rd-state-bg:{state[1]}">
    <span class="rd-answer__badge">{badge}</span>
    <p>{answer}</p>
  </div>
  <div class="rd-tiles">
{tiles_html}
  </div>
  <div class="rd-line" id="the-line">
    <h3>Where the line is</h3>
    <p><strong>vfairness is beta-ready when all {len(beta)} conditions below are met. Not most of
    them: all of them.</strong> Together they say that every number the library returns has been
    checked by a program, against an established library or against data where the number
    cannot exist, that nothing known is broken, and that every piece of code has been run at least
    once. Today {n_ok} of {len(beta)} are met.</p>
  </div>
  <table class="rd-conds" id="conditions"><tbody>{conds}</tbody></table>
  <div class="rd-line rd-line--later" id="for-1-0">
    <h3>Not required for beta, required for the 1.0 release</h3>
    <p>A second, independent examiner for every one of the code units, not only for the ones
    that return numbers. Decided on 1 Oct 2026: for every capability that returns a fairness
    number, the last two beta conditions already re-check it by running it, which is stronger
    than a second opinion. For the rest (rendering, tooling, plumbing) a second examiner is still
    owed, and it is listed here and in the heat map until it is done.</p>
    <table class="rd-conds"><tbody>{later_rows}</tbody></table>
  </div>

  <h2 id="rely">What you can rely on</h2>
  <div class="rd-cols">
{cols}
  </div>

  <h2 id="heatmap">Where each part of the library stands</h2>
  <p class="rd-stamp"><strong>As of {_date(asof)}.</strong> The last two columns were run on
  {_date(gate.get("date", ""))}. The first three come from the examination record, whose newest
  evidence is dated {_date(led.get("newest_evidence", ""))}.</p>
  <p class="rd-note">The same facts, by area. Green is done, amber is partly done, red is not
  started or broken, grey means the condition does not apply there.</p>
  <div class="rd-scroll" style="border:0;background:none">{heat}</div>
  <div class="rd-legend"><span class="g">done</span><span class="a">partly</span><span class="r">open</span><span class="n">does not apply</span></div>

  <div class="rd-line" id="recheck-logic" style="margin-top:1.2rem">
    <h3>Why a green first column and an amber second column are not a contradiction</h3>
    <ul class="rd-logic">
      <li><strong>Examined (first column):</strong> every code unit was run, on normal and on
      broken data, by one examiner, who graded it.</li>
      <li><strong>Re-checked (second column):</strong> a second, independent examiner then tries
      to prove that grade wrong. Amber or red means this has <strong>not happened yet</strong>
      for part of the area. It does not mean the re-check failed.</li>
      <li><strong>Why the re-check matters:</strong> {recheck_sentence}</li>
      <li><strong>What protects you in the meantime:</strong> every capability that returns a
      fairness number is re-verified by a program on every build: same answer as an established
      library where one exists, and no invented number on broken data. That is a stronger check
      than a second opinion, and it is what the beta relies on.</li>
      <li><strong>What comes next:</strong> re-checking the remaining {n_unconfirmed:,} code units is
      the main work for the 1.0 release. Any grade a re-check overturns is fixed the same way as
      before.</li>
    </ul>
  </div>

  <h3 id="heatmap-guide">How to read this table</h3>
  <div class="rd-scroll"><table class="rd-table rd-guide">
    <thead><tr><th>Column</th><th>What it checks</th><th>What the number means</th>
    <th>If it is amber or red, the risk for you</th><th>What to do</th></tr></thead>
    <tbody>
    <tr><td><strong>Code units examined</strong></td>
      <td>Every public function, class and method in the area was run, on normal data and on
      broken data, and the result was written down.</td>
      <td>Examined out of all code units in the area.</td>
      <td>A unit nobody has run could give a wrong or made-up answer and no one would know.</td>
      <td>Avoid the unexamined units for decisions; the status page lists them by name.</td></tr>
    <tr><td><strong>Re-checked by a second examiner</strong></td>
      <td>A second, independent reviewer tried to prove the first grade wrong.</td>
      <td>Grades re-checked and upheld, out of all examined units. The rest are not yet
      re-checked; that is different from failing a re-check.</td>
      <td>A grade not yet re-checked is one examiner's judgement, and first grades were
      overturned about one time in three when re-checked, so an amber or red area may still
      hold problems nobody has found.</td>
      <td>For decisions with consequences, prefer green areas, or verify the result on your
      own data.</td></tr>
    <tr><td><strong>Open defects</strong></td>
      <td>Problems proved by running the code that are not fixed yet.</td>
      <td>The count of them. Zero is green.</td>
      <td>Red means there is a known way this area gives a wrong answer today.</td>
      <td>Read the open register in the full record before using that area.</td></tr>
    <tr><td><strong>Same answer as an established library</strong></td>
      <td>The number is computed by vfairness and by fairlearn, scikit-learn, statsmodels or
      scipy on the same clean data.</td>
      <td>Capabilities that match, out of those that can be compared.
      <em>No reference</em> means no other library computes it.</td>
      <td>Red: the number differs from the reference and may be wrong. Grey: its correctness
      rests on vfairness's own tests only.</td>
      <td>For grey areas, sanity-check results against what you expect from your data.</td></tr>
    <tr><td><strong>No invented numbers on broken data</strong></td>
      <td>Each measuring capability is fed data where its number cannot exist (one group, no
      rows, missing scores, a group too small) and must refuse.</td>
      <td>Capabilities that refused correctly, out of those that measure.</td>
      <td>Red: the area can report something like 0.0 ("no bias") when nothing was measured,
      which looks like a clean result and is not one.</td>
      <td>Never act on a result from a red cell without checking your group sizes and
      missing values first.</td></tr>
    </tbody></table></div>
  <p class="rd-note">Colours: <strong>green</strong> done, <strong>amber</strong> partly done,
  <strong>red</strong> not done or broken, <strong>grey</strong> does not apply. Hover a cell for
  what is missing there.</p>

  <h2 id="how-gate-works">How the gate works</h2>
  <div class="rd-steps">
    <div class="rd-step"><h3>1. Correct on normal data</h3><p>Where an established library
    computes the same number, both are run on the same clean data and must agree. A
    deliberately wrong answer is fed through the same comparison to prove it would be
    caught.</p></div>
    <div class="rd-step"><h3>2. Honest on broken data</h3><p>Every capability that measures is
    given data in which its number cannot exist. Whether it should refuse is worked out by
    counting the data, not decided by hand, and a function that refuses real data fails too.</p></div>
    <div class="rd-step"><h3>Re-run, not remembered</h3><p>Both checks are programs that run on
    every documentation build and in the test suite. Each was tested by breaking the code on
    purpose and confirming the check turned red.</p></div>
  </div>

  <h2 id="compared">Compared with established libraries</h2>
  <p class="rd-note">Each capability was computed by vfairness and by the library named, on two
  clean datasets, and the two answers compared to the ninth decimal.</p>
  <div class="rd-libs">{libs}</div>
  <details class="rd-more"><summary>Every comparison, capability by capability</summary>
  <div class="rd-scroll"><table class="rd-table">
    <thead><tr><th>Capability</th><th>Compared with</th><th>Result</th></tr></thead>
    <tbody>{rows}</tbody>
  </table></div></details>
  <details class="rd-more"><summary>The {c1.get("no_reference", 0)} capabilities no outside library computes</summary>
  <p class="rd-note">{noref_list}</p></details>

  <h2 id="story">How it got here</h2>
  <p class="rd-note">Weeks of work, in five steps. The figures are as measured on each date.</p>
  <ul class="rd-time">{timeline}</ul>

  <h2 id="full-record-link">The full record</h2>
  <p class="rd-note">Everything above is a summary. The method, every test strand, every audit
  wave and the complete open register follow below, closed by default.</p>
</section>
{END}"""


def stamp(write: bool) -> bool:
    text = PAGE.read_text(encoding="utf-8")
    if START not in text or END not in text:
        raise SystemExit(f"{PAGE} has lost its readiness markers")
    head, _s, tail = text.partition(START)
    _old, _e, rest = tail.partition(END)
    new = head + render() + rest
    if write and new != text:
        PAGE.write_text(new, encoding="utf-8")
    return new == text


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()
    same = stamp(write=not a.check)
    if a.check and not same:
        print(
            "STALE: the readiness block does not match its inputs; run scripts/render_readiness.py"
        )
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
