#!/usr/bin/env python3
"""Put the three-state status where the capability is described, not in a footnote.

WHY THIS EXISTS. The status of every capability was measured and then published
in one place a reader never visits: a JSON file. The page where somebody decides
whether to call `detect_representation_bias` said nothing about whether anybody
has ever checked it. A measurement nobody can see at the point of decision is not
transparency, and this repository has already shipped the same shape of defect one
layer down: a verdict computed correctly and dropped at the boundary.

WHAT IT STAMPS, all from docs/capability-status.json, all idempotent:

  1. the published API reference page: a badge beside every documented symbol,
  2. docs/API_REFERENCE.md: the same badge as a markdown line under its heading,
  3. docs/site/status/index.html: the whole grid, all 1,558 units, searchable,
  4. the CSS for the badge, appended once to the one stylesheet the site uses.

STATIC, not fetched at render time. The site already binds numbers client-side and
that is fine for a KPI tile; it is not fine here. A badge that disappears when a
fetch fails leaves the page reading exactly as it did before any of this existed,
and a reader cannot tell "no badge" from "not checked". Stamped into the HTML, the
badge is in view-source, it is in the published artifact, and a test can compare
it against the ledger.

AMBIGUITY, resolved the safe way. One documented name can cover several code
units: `identify_proxy_variables` is documented twice and exists on two classes,
and a class badge has to answer for the methods a user reaches through it. When a
name covers several units the badge shows the WORST of them, in this order:

    FIX PENDING  >  NOT CHECKED  >  CHECKED

An open defect anywhere behind a name is the thing the reader most needs to know;
an unexamined unit behind a name is not something a badge may round up to checked.

Usage:
    python scripts/stamp_status_badges.py
    python scripts/stamp_status_badges.py --check     # exit 1 if any page is stale
"""

from __future__ import annotations

import argparse
import collections
import html
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
LEDGER = ROOT / "docs" / "capability-status.json"
SITE = ROOT / "docs" / "site"
API_PAGE = SITE / "api-reference" / "index.html"
API_MD = ROOT / "docs" / "API_REFERENCE.md"
GRID_PAGE = SITE / "status" / "index.html"
QUALITY_PAGE = SITE / "quality-and-hardening" / "index.html"
STYLES = SITE / "css" / "styles.css"

CHECKED, FIX_PENDING, NOT_CHECKED = "CHECKED", "FIX PENDING", "NOT CHECKED"
WORST_FIRST = [FIX_PENDING, NOT_CHECKED, CHECKED]
SLUG = {CHECKED: "checked", FIX_PENDING: "fix-pending", NOT_CHECKED: "not-checked"}
SHORT = {CHECKED: "Checked", FIX_PENDING: "Fix pending", NOT_CHECKED: "Not checked"}

BADGE_OPEN, BADGE_CLOSE = "<!--cap-status-->", "<!--/cap-status-->"
CSS_MARK = "/* cap-status badges: generated by scripts/stamp_status_badges.py */"


def load() -> dict:
    if not LEDGER.exists():
        raise SystemExit("docs/capability-status.json missing; run scripts/capability_status.py")
    return json.loads(LEDGER.read_text(encoding="utf-8"))


def index_by_name(units: dict) -> dict[str, list[str]]:
    """short name -> every unit it could mean, class methods folded into the class."""
    by_tail: dict[str, list[str]] = collections.defaultdict(list)
    for qual in units:
        by_tail[qual.split(".")[-1]].append(qual)
    out: dict[str, list[str]] = {}
    for name, quals in by_tail.items():
        covered = list(quals)
        for qual in quals:
            if units[qual]["kind"] == "class":
                # A user reaching `Thing().method()` is relying on the methods,
                # so the class badge answers for them too.
                covered += [q for q in units if q.startswith(qual + ".")]
        out[name] = sorted(set(covered))
    return out


def verdict(units: dict, quals: list[str]) -> tuple[str, str]:
    """(status, tooltip) for a documented name covering `quals`."""
    statuses = [units[q]["status"] for q in quals]
    status = next(s for s in WORST_FIRST if s in statuses)
    counts = collections.Counter(statuses)
    if len(quals) == 1:
        tip = units[quals[0]]["detail"]
    else:
        parts = [f"{counts[s]} {SHORT[s].lower()}" for s in WORST_FIRST if counts[s]]
        tip = f"{len(quals)} code units behind this name: " + ", ".join(parts)
    return status, tip


def badge(status: str, tip: str, *, small: bool = False) -> str:
    cls = f"cap-status cap-status--{SLUG[status]}" + (" cap-status--sm" if small else "")
    return (
        f'{BADGE_OPEN}<a class="{cls}" href="../status/" '
        f'title="{html.escape(tip, quote=True)}" '
        f'data-cap-status="{status}">{SHORT[status]}</a>{BADGE_CLOSE}'
    )


# The grid is one self-contained page, so its chip is a plain span rather than a
# link into a relative path that would be wrong from there.
PREVIEW_PILL = (
    '<span class="cap-scope cap-scope--preview cap-scope--sm" '
    'title="Preview capability. Documented and usable, but not yet fully covered and checked by the beta verification programme. The beta bar certifies the core surface; this sits outside it.">Preview</span>'
)

PREVIEW_TIP = "Preview capability. Documented and usable, but not yet fully covered and checked by the beta verification programme. The beta bar certifies the core surface; this sits outside it."


def scope_chip(units: dict, quals: list[str], *, small: bool = False) -> str:
    """A Preview chip, or nothing.

    Scope is ORTHOGONAL to status, so this sits beside the badge rather than
    replacing it: a preview unit can be perfectly well CHECKED, and a core unit can
    be unexamined. Collapsing the two would lose one of them.

    It is rendered wherever a capability is described, because the cut only means
    something at the point of use. A reader who opens the API reference for an MCP
    tool has no reason to visit the page that defines the boundary, and until this
    existed nothing on their path said the beta does not cover it.
    """
    if not quals or not all(units[q].get("scope") == "preview" for q in quals):
        return ""
    cls = "cap-scope cap-scope--preview" + (" cap-scope--sm" if small else "")
    return (
        f'<a class="{cls}" href="../quality-and-hardening/#what-the-beta-covers" '
        f'title="{html.escape(PREVIEW_TIP, quote=True)}" data-cap-scope="preview">Preview</a>'
    )


def _strip_old(text: str) -> str:
    return re.sub(re.escape(BADGE_OPEN) + ".*?" + re.escape(BADGE_CLOSE), "", text, flags=re.S)


# ---------------------------------------------------------------------------
# 1. the published API reference page
# ---------------------------------------------------------------------------

_NAME_SPAN = re.compile(r'(<span class="api-function-name">)([^<]+)(</span>)')


def stamp_api_page(led: dict, *, write: bool) -> tuple[int, list[str], str]:
    units, by_name = led["units"], index_by_name(led["units"])
    text = _strip_old(API_PAGE.read_text(encoding="utf-8"))
    stamped, missing = 0, []

    def repl(m: re.Match) -> str:
        nonlocal stamped
        shown = m.group(2).strip()
        name = re.sub(r"^(class|def)\s+", "", shown).lstrip("@").split("(")[0].strip()
        name = name.split(".")[-1]
        quals = by_name.get(name)
        if not quals:
            missing.append(shown)
            return m.group(0)
        status, tip = verdict(units, quals)
        stamped += 1
        chip = scope_chip(units, quals)
        marked = badge(status, tip)
        if chip:
            marked = marked.replace(BADGE_CLOSE, chip + BADGE_CLOSE)
        return m.group(0) + marked

    text = _NAME_SPAN.sub(repl, text)
    text = _stamp_methods(text, units, missing)
    text = _stamp_legend(text, led)
    if write:
        API_PAGE.write_text(text, encoding="utf-8")
    return stamped, missing, text


# METHOD ENTRIES, added 2026-10-01. A class badge already answers for its methods
# (worst of them), but a reader looking at `fit(...)` or a row naming
# `run_toxicity` saw no label on the thing itself. These are resolved by the EXACT
# Class.method qualname, never by short name: `fit` alone names dozens of units,
# and a badge borrowed from another class's `fit` would be a claim about the wrong
# code. A method that does not resolve is reported as missing, not guessed.
_CLASS_SPAN = re.compile(r'<span class="api-function-name">\s*class\s+([A-Za-z_]\w*)')
_METHOD_BLOCK = re.compile(r'(<div class="api-method">\s*<code>)([A-Za-z_]\w*)(\([^<]*\)</code>)')
_METHOD_ROW = re.compile(r"(<tr><td><code>)([A-Za-z_]\w*)(</code>)")


def _method_quals(units: dict, cls: str, meth: str) -> list[str]:
    """Units for ``cls.meth``, following inheritance to the class that defines it.

    `GroupThresholdOptimizer.fit_predict` is defined on BaseThresholdOptimizer and
    graded there; the page documents it on the subclass a user instantiates.
    """
    quals = [q for q in units if q.endswith(f".{cls}.{meth}")]
    if quals:
        return quals
    import importlib

    for cq in (q for q in units if q.endswith(f".{cls}") and units[q]["kind"] == "class"):
        mod, _, name = cq.rpartition(".")
        try:
            obj = getattr(importlib.import_module(mod), name)
            defined = getattr(obj, meth).__qualname__  # e.g. BaseThresholdOptimizer.fit_predict
        except Exception:  # noqa: BLE001 - unresolvable stays missing, never guessed
            continue
        hit = [q for q in units if q.endswith("." + defined) and q.startswith(mod.split(".")[0])]
        if len(hit) == 1:
            return hit
    return []


def _stamp_methods(text: str, units: dict, missing: list) -> str:
    classes = [(m.start(), m.group(1)) for m in _CLASS_SPAN.finditer(text)]

    def owner(pos: int) -> str | None:
        before = [c for p, c in classes if p < pos]
        return before[-1] if before else None

    def stamp(m: re.Match) -> str:
        cls = owner(m.start())
        if not cls:
            return m.group(0)
        quals = _method_quals(units, cls, m.group(2))
        if not quals:
            missing.append(f"{cls}.{m.group(2)}")
            return m.group(0)
        status, tip = verdict(units, quals)
        return m.group(0) + badge(status, tip, small=True)

    text = _METHOD_BLOCK.sub(stamp, text)

    # Only rows of a table whose first column is "Method": other tables on the page
    # list strategy names or bands, which are not code.
    def table(m: re.Match) -> str:
        body = m.group(0)
        if not re.search(r"<thead><tr><th>Method</th>", body):
            return body
        return _METHOD_ROW.sub(stamp_at(m.start()), body)

    def stamp_at(offset: int):
        def inner(r: re.Match) -> str:
            cls = owner(offset)
            if not cls:
                return r.group(0)
            quals = _method_quals(units, cls, r.group(2))
            if not quals:
                missing.append(f"{cls}.{r.group(2)}")
                return r.group(0)
            status, tip = verdict(units, quals)
            return r.group(0) + badge(status, tip, small=True)

        return inner

    return re.sub(r'<table class="api-table">.*?</table>', table, text, flags=re.S)


_LEGEND_START, _LEGEND_END = "<!--cap-legend:start-->", "<!--cap-legend:end-->"


def _legend_html(led: dict) -> str:
    c = led["counts"]
    total = sum(c.values())
    preview_total = sum(1 for r in led["units"].values() if r.get("scope") == "preview")
    return f"""{_LEGEND_START}
<div class="cap-legend">
  <strong>Beta status on every symbol below.</strong>
  Each one carries a badge saying whether anybody has actually checked it:
  <a class="cap-status cap-status--checked cap-status--sm" href="../status/">Checked</a> graded and assessed, any defect found was fixed;
  <a class="cap-status cap-status--fix-pending cap-status--sm" href="../status/">Fix pending</a> a defect is still open, do not rely on it in the beta;
  <a class="cap-status cap-status--not-checked cap-status--sm" href="../status/">Not checked</a> nobody has established anything either way.
  Measured across the whole public surface: {c.get(CHECKED, 0)} checked, {c.get(FIX_PENDING, 0)} fix pending,
  {c.get(NOT_CHECKED, 0)} not checked, of {total} code units.
  A badge covering several units shows the worst of them.
  <br><br>
  <strong>Scope is a separate question from status.</strong> A symbol marked
  <a class="cap-scope cap-scope--preview cap-scope--sm" href="../quality-and-hardening/#what-the-beta-covers">Preview</a>
  is documented and usable, but not yet fully covered and checked by the beta
  verification programme: the beta bar certifies the core surface, and these sit
  outside it. A preview symbol can be perfectly well checked, and a core symbol can
  be unexamined, so the two labels are shown side by side rather than merged.
  {preview_total} of {total} code units are preview; what is in each and why is in
  <a href="../quality-and-hardening/#what-the-beta-covers">what the beta covers</a>.
  Full grid: <a href="../status/">status of every capability</a>.
</div>
{_LEGEND_END}"""


def _stamp_legend(text: str, led: dict) -> str:
    block = _legend_html(led)
    if _LEGEND_START in text:
        return re.sub(
            re.escape(_LEGEND_START) + ".*?" + re.escape(_LEGEND_END),
            lambda _m: block,
            text,
            flags=re.S,
        )
    # Before the first documented symbol, so a reader meets the legend first.
    anchor = text.find('<div class="api-function">')
    if anchor == -1:
        return text
    return text[:anchor] + block + "\n" + text[anchor:]


# ---------------------------------------------------------------------------
# 2. the markdown API reference
# ---------------------------------------------------------------------------

# A TABLE ROW whose first cell names a callable. The API reference documents 100
# code units this way and only 86 under a heading, so badging headings alone left
# most of the described surface unlabelled: the badge has to be where the reader
# meets the capability, and for a method summary table that is the row.
_MD_TABLE_ROW = re.compile(r"^\|\s*[`@]?([A-Za-z_][A-Za-z0-9_.]*)\(?\)?`?\s*\|(.*)\|\s*$", re.M)
_ROW_OPEN, _ROW_CLOSE = "<!--cs-->", "<!--/cs-->"

_MD_HEADING = re.compile(r"^(#{2,4})\s+[`@]?([A-Za-z_][A-Za-z0-9_.]*)[`]?(?:\(\))?(\s+.*)?$", re.M)
_MD_MARK = "<!-- cap-status:"
_MD_END = "<!-- /cap-status -->"


def stamp_api_md(led: dict, *, write: bool) -> tuple[int, str]:
    units, by_name = led["units"], index_by_name(led["units"])
    # Strip the WHOLE previous block, delimiters and body. Stripping only the
    # opening comment left the status line behind, so a second run stacked a
    # second one under the same heading: the check then reported the file stale
    # immediately after stamping it, which is how the bug surfaced.
    text = re.sub(
        r"\n?" + re.escape(_MD_MARK) + r".*?" + re.escape(_MD_END) + r"\n",
        # Empty, not "\n". The heading's own newline is still in the untouched
        # remainder, so putting one back accumulated a blank line per run and the
        # file was never byte-identical twice. Idempotence is the whole contract
        # here: a stamper that changes the file every time it is asked to check it
        # makes its own drift guard meaningless.
        "",
        API_MD.read_text(encoding="utf-8"),
        flags=re.S,
    )
    out, stamped, last = [], 0, 0
    for m in _MD_HEADING.finditer(text):
        quals = by_name.get(m.group(2).split(".")[-1])
        if not quals:
            continue
        status, tip = verdict(units, quals)
        out.append(text[last : m.end()])
        scope = (
            " **Preview:** documented and usable, and not yet fully covered and "
            "checked by the beta verification programme."
            if all(units[q].get("scope") == "preview" for q in quals)
            else ""
        )
        out.append(
            f"\n{_MD_MARK} {m.group(2)} -->\n"
            f"**Beta status: {SHORT[status]}.** {tip}{scope}\n{_MD_END}\n"
        )
        last = m.end()
        stamped += 1
    out.append(text[last:])
    new = _stamp_table_rows("".join(out), units, by_name)
    if write:
        API_MD.write_text(new, encoding="utf-8")
    return stamped, new


def _stamp_table_rows(text: str, units: dict, by_name: dict) -> str:
    """Badge every table row whose first cell names a code unit. Idempotent.

    Strips the whole previous marker INCLUDING the space before it, so the row is
    byte-identical after a second run: the heading stamper shipped with exactly
    that bug and its own drift check caught it.
    """
    text = re.sub(r" ?" + re.escape(_ROW_OPEN) + r".*?" + re.escape(_ROW_CLOSE), "", text)

    def repl(m: re.Match) -> str:
        name = m.group(1).split(".")[-1]
        quals = by_name.get(name)
        if not quals:
            return m.group(0)
        status, _tip = verdict(units, quals)
        row = m.group(0).rstrip()
        assert row.endswith("|")
        return f"{row[:-1].rstrip()} {_ROW_OPEN}**[{SHORT[status]}]**{_ROW_CLOSE} |"

    return _MD_TABLE_ROW.sub(repl, text)


# ---------------------------------------------------------------------------
# 3. the grid
# ---------------------------------------------------------------------------


def _independent_check() -> tuple[set, int | None, int | None]:
    """(units nobody has independently checked, overturned ever, audited ever).

    Read from the register at render time, never written into this page by hand,
    so the number a reader meets here cannot drift from the one the gate measures.
    If the register cannot be read, the overturn figures come back None and the
    page says it could not state them rather than quoting a remembered one.
    """
    import sys

    sys.path.insert(0, str(Path(__file__).resolve().parent))
    try:
        import library_kpis as _K

        graded = _K.graded_items()
        g = _K.grading()
    except Exception:
        return set(), None, None
    unaudited = {q for q, rec in graded.items() if not rec.get("audited")}
    return unaudited, g.get("audit_overturned_ever"), g.get("audited_ever")


def grid_html(led: dict) -> str:
    units = led["units"]
    c = led["counts"]
    total = sum(c.values())
    # NOT INDEPENDENTLY CHECKED, on the page a reader actually opens, beside every
    # count it qualifies. Until 2026-09-30 this page carried Checked / Fix pending /
    # Not checked only, and the first-examination wave that day moved Core "not
    # checked" from 173 to 6 while moving "nobody else has tried to refute this"
    # from 131 to 612. A page showing only the first number reported that day as
    # pure progress. The markdown status page was updated first and this one was
    # missed, which is the exact failure the standing rule about rendered views
    # exists for, so both are now generated from the same register.
    unaudited, overturned, audited_ever = _independent_check()
    by_area = collections.defaultdict(collections.Counter)
    unaudited_by_area = collections.Counter()
    by_scope = collections.defaultdict(collections.Counter)
    unaudited_by_scope = collections.Counter()
    for q, r in units.items():
        by_area[r["area"]][r["status"]] += 1
        sc = r.get("scope") or "other"
        by_scope[sc][r["status"]] += 1
        if q in unaudited:
            unaudited_by_area[r["area"]] += 1
            unaudited_by_scope[sc] += 1
    area_rows = "\n".join(
        f'<tr><td>{html.escape(a)}</td><td class="n">{by_area[a][CHECKED]}</td>'
        f'<td class="n">{by_area[a][FIX_PENDING]}</td><td class="n">{by_area[a][NOT_CHECKED]}</td>'
        f'<td class="n">{sum(by_area[a].values())}</td>'
        f'<td class="n">{unaudited_by_area[a]}</td></tr>'
        for a in sorted(by_area, key=lambda a: -sum(by_area[a].values()))
    )
    scope_labels = {
        "core": "Core: what the beta promises",
        "preview": "Preview: documented, not certified",
        "other": "Other",
    }
    scope_rows = "\n".join(
        f"<tr><td>{scope_labels.get(sc, html.escape(sc))}</td>"
        f'<td class="n">{sum(by_scope[sc].values())}</td>'
        f'<td class="n">{by_scope[sc][CHECKED]}</td>'
        f'<td class="n">{by_scope[sc][FIX_PENDING]}</td>'
        f'<td class="n">{by_scope[sc][NOT_CHECKED]}</td>'
        f'<td class="n">{unaudited_by_scope[sc]}</td></tr>'
        for sc in ("core", "preview", "other")
        if by_scope.get(sc)
    )
    if overturned and audited_ever:
        overturn_note = (
            f"<p><strong>Not independently checked</strong> counts grades one examiner "
            f"reached and nobody has yet tried to refute. Of the grades that HAVE been "
            f"through that second examination, <strong>{overturned} of {audited_ever} "
            f"({100 * overturned / audited_ever:.0f}%) were overturned</strong>. So a "
            f"Checked unit in that column is a claim with evidence behind it, not a "
            f"settled result.</p>"
        )
    else:
        overturn_note = (
            "<p>The overturn rate of independently checked grades could not be read "
            "from the register here, so how far to trust an unchecked grade is NOT "
            "stated on this page.</p>"
        )
    # The area picker, and the core-path membership the filter needs, both derived
    # from the ledger so a new area appears on its own. The core areas are read from
    # the ledger rather than imported, so there is one definition of the boundary
    # and this page cannot drift from the page that publishes it.
    core_areas = sorted(led.get("tier1_areas") or [])
    area_options = "".join(
        f"<option>{html.escape(a)}</option>"
        for a in sorted(by_area, key=lambda a: (a not in core_areas, a))
    )
    core_json = json.dumps(core_areas)
    rows = "\n".join(
        f'<tr data-status="{r["status"]}" data-area="{html.escape(r["area"])}">'
        f'<td class="u"><code>{html.escape(q)}</code></td>'
        f'<td><span class="cap-status cap-status--{SLUG[r["status"]]} cap-status--sm">{SHORT[r["status"]]}</span>'
        f"{'' if r.get('scope') != 'preview' else chr(32) + PREVIEW_PILL}</td>"
        f"<td>{html.escape(r['area'])}</td><td>{r['kind']}</td>"
        f'<td class="d">{html.escape(r["detail"])}</td></tr>'
        for q, r in sorted(units.items())
    )
    return f"""<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Status of every capability | vfairness</title>
<meta name="description" content="The beta status of all {total} public code units in vfairness: checked, fix pending, or not checked, with the reason for each.">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;0,800;1,300;1,400&family=JetBrains+Mono:wght@400;500&display=swap">
<link rel="stylesheet" href="../css/styles.css">
    <script>/* theme before first paint: vf-theme = light | dark | system */(function(){{var m='system';try{{m=localStorage.getItem('vf-theme')||'system'}}catch(e){{}}var d=m==='dark'||(m==='system'&&window.matchMedia&&matchMedia('(prefers-color-scheme: dark)').matches);var r=document.documentElement;r.setAttribute('data-theme',d?'dark':'light');r.setAttribute('data-theme-mode',m)}})()</script>
<style>
 .grid-wrap{{max-width:1200px;margin:0 auto;padding:2rem 16px}}
 table.grid{{width:100%;border-collapse:collapse;font-size:.85rem}}
 table.grid th,table.grid td{{text-align:left;padding:.4rem .5rem;border-bottom:1px solid rgba(128,128,128,.25);vertical-align:top}}
 table.grid td.n,table.grid th.n{{text-align:right}}
 table.grid td.u code{{font-size:.78rem;word-break:break-all}}
 table.grid td.d{{color:var(--color-gray-500,#6b7280);max-width:36rem}}
 .controls{{display:flex;gap:.5rem;flex-wrap:wrap;margin:1rem 0}}
 .controls input,.controls select{{padding:.4rem .6rem;font:inherit}}
</style>
</head><body>
<div class="grid-wrap">
<h1>Status of every capability</h1>
<p><strong>{total} public code units, none of them silent.</strong> This is the whole
public surface of the library, measured on {html.escape(str(led.get("measured_on")))} and regenerated by
<code>scripts/capability_status.py</code>. Nothing here is typed by hand.</p>
<ul>
<li><span class="cap-status cap-status--checked cap-status--sm">Checked</span>
 graded and assessed. It was executed on healthy input and on input where the thing it
 measures does not exist. If it was found inventing a value, that was fixed.
 <strong>{c.get(CHECKED, 0)}</strong> units.</li>
<li><span class="cap-status cap-status--fix-pending cap-status--sm">Fix pending</span>
 graded and assessed, and a defect is still open. Do not rely on it in the beta.
 <strong>{c.get(FIX_PENDING, 0)}</strong> units.</li>
<li><span class="cap-status cap-status--not-checked cap-status--sm">Not checked</span>
 nobody has established anything either way. We are blind here. It may be perfectly
 correct; this state is the absence of a measurement, not a failed one.
 <strong>{c.get(NOT_CHECKED, 0)}</strong> units.</li>
</ul>
<p><strong>Checked is not a correctness certificate</strong> for the number a function
returns. It means the fabrication class was examined: on input where nothing is
measurable, the unit refuses instead of handing back a neutral-looking value. The
reason column states what each row does and does not establish.</p>
<p>The same rows as a machine-readable feed:
<a href="../data/capability-status.json"><code>capability-status.json</code></a>.
One object per code unit, carrying its state, the reason, the evidence it rests on
and the tests that pin it, so a claim on this page can be checked rather than
taken.</p>
<h2>By scope</h2>
<table class="grid"><thead><tr><th>Scope</th><th class="n">Units</th><th class="n">Checked</th><th class="n">Fix pending</th><th class="n">Not checked</th><th class="n">Not independently checked</th></tr></thead>
<tbody>
{scope_rows}
</tbody></table>
{overturn_note}
<h2>By area</h2>
<table class="grid"><thead><tr><th>Area</th><th class="n">Checked</th><th class="n">Fix pending</th><th class="n">Not checked</th><th class="n">Total</th><th class="n">Not independently checked</th></tr></thead>
<tbody>
{area_rows}
</tbody></table>
<h2>Every unit</h2>
<div class="controls">
 <input id="q" type="search" placeholder="filter by name, area or reason" aria-label="filter">
 <select id="s"><option value="">every status</option><option>CHECKED</option><option>FIX PENDING</option><option>NOT CHECKED</option></select>
 <select id="a"><option value="">every area</option><option value="core">Core (what the beta covers)</option>{area_options}</select>
 <span id="count"></span>
</div>
<table class="grid" id="t"><thead><tr><th>Code unit</th><th>Status</th><th>Area</th><th>Kind</th><th>What is established</th></tr></thead>
<tbody>
{rows}
</tbody></table>
</div>
<script>
(function(){{
 /* The AREA filter, and the "core" option in particular, exists so the boundary is
    something a reader can inspect rather than a phrase. Core is what the beta
    promises, and its counts only mean anything beside the number of its units
    nobody has examined; both are one click away here. */
 var CORE={core_json};
 var q=document.getElementById('q'),s=document.getElementById('s'),a=document.getElementById('a'),
     rows=[].slice.call(document.querySelectorAll('#t tbody tr')),c=document.getElementById('count');
 function inArea(r){{
  var v=a.value; if(!v) return true;
  var ar=r.getAttribute('data-area');
  return v==='core' ? CORE.indexOf(ar)>-1 : ar===v;
 }}
 function apply(){{
  var t=q.value.toLowerCase(),st=s.value,n=0,shown={{}};
  rows.forEach(function(r){{
   var ok=(!st||r.getAttribute('data-status')===st)&&inArea(r)&&(!t||r.textContent.toLowerCase().indexOf(t)>-1);
   r.style.display=ok?'':'none';
   if(ok){{n++; var k=r.getAttribute('data-status'); shown[k]=(shown[k]||0)+1;}}
  }});
  /* Say what the filtered set contains, not just how many. A count alone lets a
     reader assume the remainder is fine. */
  var parts=[]; ['CHECKED','FIX PENDING','NOT CHECKED'].forEach(function(k){{
   if(shown[k]) parts.push(shown[k]+' '+k.toLowerCase());
  }});
  c.textContent=n+' of '+rows.length+' shown'+(parts.length?' ('+parts.join(', ')+')':'');
 }}
 /* ?area=core and ?status=NOT+CHECKED make a specific claim linkable. */
 var params=new URLSearchParams(location.search);
 if(params.get('area')) a.value=params.get('area');
 if(params.get('status')) s.value=params.get('status');
 q.addEventListener('input',apply); s.addEventListener('change',apply);
 a.addEventListener('change',apply); apply();
}})();
</script>
</body></html>
"""


# ---------------------------------------------------------------------------
# 4. the CSS
# ---------------------------------------------------------------------------

CSS = f"""
{CSS_MARK}
/* Outlined mono chips, matching the site's one chip language. The dark
   variants key on the site's own theme switch (html[data-theme="dark"]),
   NOT on prefers-color-scheme: the old OS-keyed block turned these badges
   dark on a page that stayed light, measured at 1.6:1 on 2026-10-01. */
.cap-status{{display:inline-block;padding:.1rem .45rem;margin-left:.45rem;border-radius:0;
 font-family:var(--font-mono,ui-monospace,monospace);font-size:.64rem;font-weight:500;letter-spacing:.08em;
 text-transform:uppercase;text-decoration:none;white-space:nowrap;
 border:1px solid currentColor;background:transparent;vertical-align:middle}}
.cap-status::before{{content:"";display:inline-block;width:6px;height:6px;margin-right:5px;
 border-radius:50%;background:currentColor;vertical-align:1px}}
.cap-status--sm{{font-size:.6rem;margin-left:.25rem}}
.cap-status--checked{{color:#1d7a3a}}
.cap-status--fix-pending{{color:#b42318}}
.cap-status--not-checked{{color:#5a6972}}
/* Scope sits beside status, never instead of it, and is deliberately quieter:
   preview is a statement about our promise, not a warning about the code. */
.cap-scope{{display:inline-block;padding:.1rem .45rem;margin-left:.3rem;border-radius:0;
 font-family:var(--font-mono,ui-monospace,monospace);font-size:.64rem;font-weight:500;letter-spacing:.08em;
 text-transform:uppercase;text-decoration:none;white-space:nowrap;
 border:1px dashed currentColor;background:transparent;color:#8a5a00;vertical-align:middle}}
.cap-scope--sm{{font-size:.6rem;margin-left:.25rem}}
.cap-legend{{margin:1.25rem 0;padding:.9rem 1rem;border-left:2px solid #293b51;background:#f4f3f1;
 font-size:.85rem;line-height:1.6}}
html[data-theme="dark"] .cap-status--checked{{color:#7fd36a}}
html[data-theme="dark"] .cap-status--fix-pending{{color:#f0957d}}
html[data-theme="dark"] .cap-status--not-checked{{color:#9aa8b5}}
html[data-theme="dark"] .cap-scope{{color:#e8b24f}}
html[data-theme="dark"] .cap-legend{{border-left-color:#c5ced7;background:#17222e}}
"""


def stamp_css(*, write: bool) -> bool:
    text = STYLES.read_text(encoding="utf-8")
    if CSS_MARK in text:
        head, _sep, _tail = text.partition(CSS_MARK)
        new = head.rstrip() + "\n" + CSS.strip() + "\n"
    else:
        new = text.rstrip() + "\n\n" + CSS.strip() + "\n"
    if new != text and write:
        STYLES.write_text(new, encoding="utf-8")
    return new != text


_SITE_START, _SITE_END = "<!-- STATUS:site:start -->", "<!-- STATUS:site:end -->"


def _pct(n: int, d: int) -> str:
    return f"{100.0 * n / d:.1f}%" if d else "n/a"


def _site_summary(led: dict) -> str:
    """The three-state table for the published quality page.

    Rendered, not typed. Every hardcoded figure on this site has rotted at least
    once: a chunk count stale for months, a test count stale by 3,700, and a tile
    row adding two different countings of the same surface.
    """
    units = led["units"]
    total = len(units)
    counts = collections.Counter(r["status"] for r in units.values())
    # READ THE BOUNDARY, NEVER RESTATE IT. This was a literal tuple of three area
    # names, a second copy of a definition that lives in capability_status.py. When
    # the core was widened the definition moved and this copy did not, so the page
    # carried a section saying core is 1,382 units directly above a table saying it
    # is 390. One boundary, one place, read from the ledger that publishes it.
    core_areas = set(led.get("core_areas") or led.get("tier1_areas") or [])
    core = collections.Counter(r["status"] for r in units.values() if r["area"] in core_areas)
    core_total = sum(core.values())
    _named = sorted(core_areas)
    # Names as the ledger spells them: lowercasing turns "CI/CD gates" into
    # "ci/cd gates" and "Explainability (XAI)" into "(xai)".
    core_named = (
        ", ".join(_named[:-1]) + " and " + _named[-1]
        if len(_named) > 1
        else (_named[0] if _named else "not defined")
    )
    # EVERY CELL CARRIES A kpi- CLASS. This table was generated, so its figures were
    # never typed, but generated is only half of it: the page is served for as long
    # as it stands and this block was right at BUILD time alone, while the board one
    # screen above it refilled from library-stats.json on every load. Two tables of
    # the same ledger, one live and one frozen, is the drift this page exists about.
    # The literals here are the no-JavaScript fallback and stay correct because this
    # function writes them; tests/test_kpi_spans_are_live.py refuses a class that
    # renders two different values, so they cannot part company with the board's.
    rows = []
    for state, cls, share_cls in (
        (CHECKED, "kpi-ledger-checked", "kpi-share-checked"),
        (FIX_PENDING, "kpi-ledger-fix-pending", "kpi-share-fix"),
        (NOT_CHECKED, "kpi-ledger-not-checked", "kpi-share-unchecked"),
    ):
        core_cls = "kpi-core-" + {"CHECKED": "checked", "FIX PENDING": "fix"}.get(
            state, "unchecked"
        )
        share = _pct(counts[state], total)
        rows.append(
            f'<tr><td><span class="cap-status cap-status--{SLUG[state]} cap-status--sm">'
            f"{SHORT[state]}</span></td>"
            f'<td style="text-align:right"><span class="{cls}">{counts[state]:,}</span></td>'
            f'<td style="text-align:right"><span class="{share_cls}">'
            f"{share.rstrip('%')}</span>{'%' if share.endswith('%') else ''}</td>"
            f'<td style="text-align:right"><span class="{core_cls}">{core[state]:,}</span></td>'
            "</tr>"
        )
    dates = ", ".join(led.get("evidence_dates") or [])

    # THE SCOPE TABLE AND THE COLUMN THAT QUALIFIES IT, on the page Daniel reads.
    # Added 2026-10-01 after this exact table went onto the status page and into
    # CAPABILITY_STATUS.md while THIS page, the one he linked and reads, still had
    # neither. He reads HTML, not markdown, so a figure that is only in a .md file
    # has not been published to him. "Checked" means one examiner ran a unit and
    # recorded a result; the last column says how many of those results nobody has
    # yet tried to refute, and the sentence under it says how often that has failed.
    unaudited, overturned, audited_ever = _independent_check()
    scope = collections.defaultdict(collections.Counter)
    scope_unaudited = collections.Counter()
    for q, r in units.items():
        sc = "core" if r["area"] in core_areas else "preview"
        scope[sc][r["status"]] += 1
        if q in unaudited:
            scope_unaudited[sc] += 1
    scope_rows = []
    for sc, label in (
        ("core", "Core: what the beta promises"),
        ("preview", "Preview: documented, not certified"),
    ):
        c = scope[sc]
        scope_rows.append(
            f"<tr><td>{label}</td>"
            f'<td style="text-align:right">{sum(c.values()):,}</td>'
            f'<td style="text-align:right">{c[CHECKED]:,}</td>'
            f'<td style="text-align:right">{c[FIX_PENDING]:,}</td>'
            f'<td style="text-align:right">{c[NOT_CHECKED]:,}</td>'
            f'<td style="text-align:right"><strong>{scope_unaudited[sc]:,}</strong></td></tr>'
        )
    tot = scope["core"] + scope["preview"]
    scope_rows.append(
        f"<tr><td><strong>Total</strong></td>"
        f'<td style="text-align:right"><strong>{sum(tot.values()):,}</strong></td>'
        f'<td style="text-align:right"><strong>{tot[CHECKED]:,}</strong></td>'
        f'<td style="text-align:right"><strong>{tot[FIX_PENDING]:,}</strong></td>'
        f'<td style="text-align:right"><strong>{tot[NOT_CHECKED]:,}</strong></td>'
        f'<td style="text-align:right"><strong>{sum(scope_unaudited.values()):,}</strong></td></tr>'
    )
    if overturned and audited_ever:
        overturn_sentence = (
            f"<strong>Not independently checked</strong> counts grades one examiner "
            f"reached and nobody has yet tried to refute. Of the grades that HAVE been "
            f"through that second examination, <strong>{overturned:,} of "
            f"{audited_ever:,} ({100 * overturned / audited_ever:.0f}%) were "
            f"overturned</strong>, so a Checked unit in that column is a claim with "
            f"evidence behind it, not a settled result."
        )
    else:
        overturn_sentence = (
            "The overturn rate of independently checked grades could not be read here, "
            "so how far to trust an unchecked grade is NOT stated on this page."
        )
    scope_table = (
        '                    <h3 id="by-scope">Where the library stands, by scope</h3>\n'
        '                    <div class="table-container">\n'
        '                    <table class="qa-table">\n'
        "                      <thead><tr><th>Scope</th>"
        '<th style="text-align:right">Units</th>'
        '<th style="text-align:right">Checked</th>'
        '<th style="text-align:right">Fix pending</th>'
        '<th style="text-align:right">Not checked</th>'
        '<th style="text-align:right">Not independently checked</th></tr></thead>\n'
        "                      <tbody>\n"
        + "\n".join("                      " + r for r in scope_rows)
        + "\n                      </tbody>\n                    </table>\n"
        "                    </div>\n"
        f'                    <p class="qa-note">{overturn_sentence}</p>\n'
    )
    return f"""{_SITE_START}
{scope_table}                    <div class="table-container">
                    <table class="qa-table">
                      <thead><tr><th>State</th><th style="text-align:right">All code units</th>
                      <th style="text-align:right">Share</th>
                      <th style="text-align:right">Core</th></tr></thead>
                      <tbody>
{chr(10).join("                      " + r for r in rows)}
                      <tr><td><strong>Total</strong></td>
                      <td style="text-align:right"><strong class="kpi-ledger-total">{total:,}</strong></td>
                      <td style="text-align:right">100%</td>
                      <td style="text-align:right"><strong class="kpi-core-total">{core_total:,}</strong></td></tr>
                      </tbody>
                    </table>
                    </div>
                    <p class="qa-note">Assembled by <code>scripts/capability_status.py</code> from
                    evidence dated {dates}. <strong>Core</strong> is what the beta promises: every
                    area this project publishes a guide or a product page for, plus the top-level
                    namespace. That is {core_named}. The rest is
                    <a href="#what-the-beta-covers">preview</a>: documented and usable, and not
                    covered by the beta bar.</p>
{_SITE_END}"""


def stamp_quality_page(led: dict, *, write: bool) -> str:
    text = QUALITY_PAGE.read_text(encoding="utf-8")
    if _SITE_START not in text or _SITE_END not in text:
        raise SystemExit(f"{QUALITY_PAGE} has lost its status markers")
    head, _s, tail = text.partition(_SITE_START)
    _old, _e, rest = tail.partition(_SITE_END)
    new = head + _site_summary(led) + rest
    if write and new != text:
        QUALITY_PAGE.write_text(new, encoding="utf-8")
    return new


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    led = load()
    write = not args.check

    stamped, missing, api_text = stamp_api_page(led, write=write)
    md_count, md_text = stamp_api_md(led, write=write)
    grid = grid_html(led)
    quality_text = stamp_quality_page(led, write=write)
    css_changed = stamp_css(write=write)
    if write:
        GRID_PAGE.parent.mkdir(parents=True, exist_ok=True)
        GRID_PAGE.write_text(grid, encoding="utf-8")

    if args.check:
        stale = []
        if API_PAGE.read_text(encoding="utf-8") != api_text:
            stale.append("docs/site/api-reference/index.html")
        if API_MD.read_text(encoding="utf-8") != md_text:
            stale.append("docs/API_REFERENCE.md")
        if not GRID_PAGE.exists() or GRID_PAGE.read_text(encoding="utf-8") != grid:
            stale.append("docs/site/status/index.html")
        if QUALITY_PAGE.read_text(encoding="utf-8") != quality_text:
            stale.append("docs/site/quality-and-hardening/index.html")
        if css_changed:
            stale.append("docs/site/css/styles.css")
        for s in stale:
            print(f"STALE: {s} does not match the ledger; run scripts/stamp_status_badges.py")
        return 1 if stale else 0

    print(f"api reference page: {stamped} symbols badged")
    print(
        f"API_REFERENCE.md:   {md_count} headings badged, "
        f"{md_text.count(_ROW_OPEN)} table rows badged"
    )
    print(f"status grid:        {sum(led['counts'].values())} units")
    print("quality page:       three-state summary rendered")
    if missing:
        # Not silent: a symbol the page documents and the surface does not have is
        # a finding about the page, and it is exactly what the docs audits keep
        # finding by hand.
        print(f"NOT ON THE PUBLIC SURFACE ({len(missing)}): {', '.join(sorted(set(missing))[:12])}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
